Repository tarantool/tarantool, pull requests merged in 2021-11, with the labels that each got.

#6625 test: fix flaky read_only_reason test
  test/replication-luatest/gh_5568_read_only_reason_test.lua
Labels: flaky test

#6626 test: make replication-luatest parallel
  test/replication-luatest/suite.ini
Labels: qa

#6645 ci: run 'integration.yml' WF in pre-commit testing
  .github/workflows/integration.yml
Labels: full-ci

#6658 Several coverity fixes
  src/box/box.cc
  src/box/memtx_rtree.c
  src/box/sql/func.c
  src/box/sql/mem.c
  src/box/sql/select.c
  src/lib/core/tt_static.h
Labels: bug
