Repository tarantool/tarantool, pull requests merged in 2021-06, with the labels that each got.

#6125 vinyl: fix adding the same tx twice to the list of writers
  src/box/vy_tx.c
  test/vinyl/gh-5934-dupicate-tx-writers.result
  test/vinyl/gh-5934-dupicate-tx-writers.test.lua
Labels: vinyl

#6146 test: fix status check in replication/transaction
  test/replication/suite.ini
  test/replication/transaction.result
  test/replication/transaction.test.lua
Labels: teamQ

#6153 test: flaky election_basic.test.lua test
  test/replication/election_basic.result
  test/replication/election_basic.test.lua
  test/replication/suite.ini
Labels: teamQ

#6168 test: vinyl/gh.test.lua fix mistake
  test/vinyl/gh.result
  test/vinyl/gh.test.lua
  test/vinyl/suite.ini
Labels: draft, teamQ
