Repository tarantool/tarantool, pull requests merged in 2021-12, with the labels that each got.

#6631 vinyl: optimize deletion of compacted run files
  changelogs/unreleased/gh-6568-replica-initial-join-removal-of-compacted-run-files.md
  src/box/vinyl.c
  src/box/vy_run.c
  src/box/vy_run.h
  src/box/vy_scheduler.c
  test/vinyl-luatest/gh_6568_replica_initial_join_removal_of_compacted_run_files_test.lua
  test/vinyl-luatest/suite.ini
Labels: full-ci

#6682 replication: fix flaky gh-3160-misc... test
  test/replication/gh-3160-misc-heartbeats-on-master-changes.result
  test/replication/gh-3160-misc-heartbeats-on-master-changes.test.lua
  test/replication/suite.ini
Labels: full-ci

#6671 test: fix flaky read_only_reason test
  test/luatest_helpers/server.lua
  test/replication-luatest/gh_5568_read_only_reason_test.lua
Labels: qa, flaky test

#6693 test: mark #6198 test `long run`
  test/box-tap/suite.ini
Labels: qa, flaky test, teamC, full-ci

#6667 test: fix flaky test on temp space truncate
  test/replication-luatest/gh_6123_truncate_temp_space_test.lua
Labels: full-ci

#6649 cmake: align folders dependencies
  CMakeLists.txt
  cmake/FindOptionalPackage.cmake
  cmake/atomic.cmake
  cmake/module.cmake
  cmake/os.cmake
  cmake/profile.cmake
  cmake/utils.cmake
  extra/CMakeLists.txt
  perf/CMakeLists.txt
  src/CMakeLists.txt
  src/box/CMakeLists.txt
  src/lib/uri/CMakeLists.txt
  test/box-tap/CMakeLists.txt
  test/unit/CMakeLists.txt
Labels: full-ci

#6700 debian: eliminate dependency from binutils package
  changelogs/unreleased/debian-remove-binutils-dependency.md
  debian/control
Labels: full-ci

#6698 Make lookup of statically built binary more robust
  static-build/CMakeLists.txt
Labels: full-ci

#6704 lib: use memcpy for unaligned load/store
  src/lib/bit/bit.h
  src/pickle.h
Labels: full-ci

#6705 cmake: fix version for Tarantool EE
  CMakeLists.txt
  test/box-py/args.result
  test/box-py/args.test.py
Labels: full-ci

#6170 test: flaky replication/long_row_timeout.test.lua
  test/replication/long_row_timeout.result
  test/replication/long_row_timeout.test.lua
  test/replication/suite.ini
Labels: teamQ, full-ci

#6714 cmake: allow to add extra export symbols
  src/CMakeLists.txt
Labels: full-ci

#6708 build: fix build with glibc-2.34
  changelogs/unreleased/gh-6686-build-with-glibc-2-34.md
  test/unit/guard.cc
Labels: build, full-ci

#6738 github-ci: Remove Ubuntu 20.10
  .github/workflows/ubuntu_20_10.yml
Labels: full-ci

#6743 github-ci: Remove Ubuntu 20.10 for arm64
  .github/workflows/ubuntu_20_10_aarch64.yml
Labels: full-ci
