Repository tarantool/tarantool, pull requests merged in 2022-11, with the labels that each got.

#7816 box: fix fkey creation together with new field names
  changelogs/unreleased/gh-7652-complex-fkey-new-field-name.md
  src/box/alter.cc
  test/engine-luatest/gh_6436_field_constraint_test.lua
  test/engine-luatest/gh_7652_complex_fkey_new_field_name_test.lua
  test/engine/ddl.result
  test/engine/json.result
  test/vinyl/errinj_ddl.result
Labels: full-ci

#7880 say: enable json log format with syslog
  changelogs/unreleased/gh-7860-syslog-json.md
  src/box/box.cc
  src/lib/core/say.c
  test/app-tap/logger.test.lua
  test/box-luatest/gh_7860_syslog_json_test.lua
  test/box-tap/cfg.test.lua
Labels: full-ci

#7868 test: remove outdated sql-tap test
  test/sql-tap/select1.test.lua
Labels: full-ci

#7885 ci, debugger: gracefully handle nil values from popen
  test/app-luatest/console_debugger_session_test.lua
Labels: full-ci

#7884 decimal: fix buffer overflow in decimal_unpack()
  src/lib/core/decimal.c
  test/unit/decimal.c
Labels: full-ci

#7875 sql: fix error with new field in new index
  changelogs/unreleased/gh-5183-fix-index-field-missing.md
  src/box/sql.c
  test/sql-luatest/gh_5183_fix_index_field_missing_test.lua
Labels: full-ci

#7872 sql: reset autoincrement IDs before execution
  changelogs/unreleased/gh-6422-autoinc-ids-reset.md
  src/box/execute.c
  src/box/sql/sqlInt.h
  src/box/sql/vdbeapi.c
  test/sql-luatest/gh_6422_autoinc_ids_reset_test.lua
Labels: full-ci

#7758 memtx: split `memtx_tx_story_unlink_both` logic in two separate contexts
  changelogs/unreleased/gh-7757-memtx-space-drop-triggers-assertion.md
  src/box/memtx_tx.c
  test/box-luatest/gh_7757_memtx_space_drop_triggers_assertion_test.lua
Labels: full-ci

#7760 memtx: add assertion and test for gap tracker retention during rollback
  src/box/memtx_tx.c
  test/box-luatest/gh_7343_unserializable_read_tracked_incorrectly_after_rollback_test.lua
Labels: full-ci

#7767 memtx secondary index uniqueness violation
  changelogs/unreleased/gh-7761-memtx-sk-index-uniqueness-violation.md
  src/box/memtx_tx.c
  test/box-luatest/gh_7761_memtx_sk_index_uniqueness_violation_test.lua
Labels: full-ci

#7852 lua/fio: clearer error msg for pread()
  src/lua/fio.lua
  test/app-luatest/gh_4963_fio_pread_err_msg_test.lua
Labels: full-ci, 2.10

#7928 test: fix flaky box-luatest/gh_7917_log_row_on_recovery_error_test
  test/box-luatest/gh_7917_log_row_on_recovery_error_test.lua
Labels: full-ci

#7934 coro: update `sp` before saving registers to a stack frame
  changelogs/unreleased/gh-7523-sigsegv-on-m1-macs.md
  third_party/coro/coro.c
Labels: full-ci

#7100 tarantoolctl: add man of flag --format for cat command
  changelogs/unreleased/gh-7099-fix-format-description-tarantoolctl-cat.md
  extra/dist/tarantoolctl.in
Labels: bug, documentation, tarantoolctl

#7935 flaky: fix flakiness of the gh_7253 test
  test/replication-luatest/gh_7253_election_long_wal_write_test.lua
Labels: full-ci

#7775 replication: invalid recovery from xlog
  changelogs/unreleased/gh-5158-invalid-recovery-from-xlog.md
  src/box/relay.cc
  test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua
Labels: full-ci

#7958 box: inherit index collation from the space format
  changelogs/unreleased/gh-5104-inherit-index-collation-from-format.md
  src/box/lua/schema.lua
  test/engine-luatest/gh_5104_inherit_index_collation_from_format_test.lua
Labels: full-ci

#7973 test: fix flaky gh_6539_log_user_space_empty_or_nil_select_test
  test/box-luatest/gh_6539_log_user_space_empty_or_nil_select_test.lua
Labels: full-ci

#7951 box: export IPROTO constants and features to Lua
  changelogs/unreleased/gh-7894-export-iproto-constants-and-features.md
  src/box/CMakeLists.txt
  src/box/iproto_constants.h
  src/box/iproto_features.h
  src/box/lua/init.c
  src/box/lua/iproto.c
  src/box/lua/iproto.h
  test/box-luatest/gh_7894_export_iproto_constants_and_features_test.lua
  test/box/misc.result
Labels: full-ci

#7879 replication: say warning if before_replace trigger changed replica_id
  changelogs/unreleased/gh_7846_before_replace_crash_on_replica_id_alter.md
  src/box/box.cc
  test/box-luatest/gh_7846_crash_on_replica_id_alter_test.lua
Labels: full-ci

#7759 memtx: fix use-after-free of successor in `tree_iterator_start`
  changelogs/unreleased/gh-7755-memtx-rev-iters-repeatable-read-violation.md
  changelogs/unreleased/gh-7756-memtx-crash-on-series-of-txs.md
  src/box/memtx_bitset.cc
  src/box/memtx_hash.cc
  src/box/memtx_rtree.cc
  src/box/memtx_tree.cc
  src/box/memtx_tx.c
  src/box/memtx_tx.h
  test/box-luatest/gh_7755_memtx_rev_iters_repeatable_read_violation_test.lua
  test/box-luatest/gh_7756_memtx_crash_on_series_of_txs_test.lua
Labels: full-ci

#7836 memtx: fix logic of read tracker rebinding during rollback
  changelogs/unreleased/gh-7828-rollback_rebind_read_tracker_wrong_idx_mask.md
  src/box/memtx_tx.c
  test/box-luatest/gh_7828_rollback_rebind_read_tracker_wrong_idx_mask_test.lua
Labels: full-ci
