Repository tarantool/tarantool, pull requests merged in 2022-08, with the labels that each got.

#7423 fiber_channel: add accessor to internal functions
  extra/exports
  src/CMakeLists.txt
  src/lib/core/fiber_channel.c
  src/symbols.c
  test/app-luatest/tnt_internal_symbol_test.lua
Labels: full-ci

#7401 sql: do nothing in ROUND() if precision is too big
  changelogs/unreleased/gh-6650-round-with-big-precision.md
  src/box/sql/func.c
  test/sql-luatest/gh_6650_round_with_big_precision_test.lua
Labels: full-ci

#7415 sql: fix wrong flag is_res_neg in sql_rem_int()
  changelogs/unreleased/gh-6575-assertion-in-modulo.md
  src/box/sql/util.c
  test/sql-luatest/gh_6575_assertion_in_modulo_test.lua
Labels: full-ci

#7416 sql: always treat NaN as NULL
  changelogs/unreleased/gh-6572-nan-is-not-null.md
  src/box/sql/mem.c
  test/sql-luatest/CMakeLists.txt
  test/sql-luatest/gh_6572_nan_is_not_null_test.c
  test/sql-luatest/gh_6572_nan_is_not_null_test.lua
Labels: full-ci

#7504 Fix a low-probability crash in our qsort implementation
  changelogs/unreleased/qsort-fix.md
  third_party/qsort_arg.c
  third_party/qsort_arg_mt.c
Labels: full-ci

#7442 static-build: bump ncurses from 6.2 to 6.3-20220716
  changelogs/unreleased/bump-ncurses-to-6.3-20220716.md
  static-build/CMakeLists.txt
Labels: full-ci

#7443 static-build: bump readline from 8.0 to 8.0p1
  changelogs/unreleased/bump-readline-to-80p1.md
  static-build/CMakeLists.txt
  static-build/readline80-001.patch
Labels: full-ci

#7516 static-build: update libiconv to 1.17 (Mac OS)
  static-build/CMakeLists.txt
Labels: full-ci

#7507 static-build: update zlib to version 1.2.12
  changelogs/unreleased/bump-zlib.md
  static-build/CMakeLists.txt
Labels: full-ci

#7529 build: fix check-dependencies test on OS X
  static-build/test/CheckDependencies.cmake
Labels: full-ci

#7426 cmake: eliminate warning about source properties
  cmake/module.cmake
Labels: code health

#7425 cmake: clean up list of API headers
  src/CMakeLists.txt
  src/box/box.cc
Labels: code health

#7527 prbuf: fix prbuf_open for empty buffer
  src/lib/core/prbuf.c
  test/unit/prbuf.c
  test/unit/prbuf.result
Labels: full-ci

#7261 lua: fix luacheck warnings in src/box/console.lua
  .luacheckrc
  src/box/lua/console.lua
Labels: full-ci

#7471 salad: rework light hash read view API
  src/box/memtx_hash.cc
  src/box/sequence.c
  src/lib/salad/light.h
  test/unit/CMakeLists.txt
  test/unit/light.cc
  test/unit/light_view.c
  test/unit/light_view.result
Labels: full-ci

#7488 memtx: fix HASH index 'GT' iterator `next` method set incorrectly
  changelogs/unreleased/gh-7477-memtx-hash-idx-gt-iter-dirty-reads.md
  src/box/memtx_hash.cc
  test/box-luatest/gh_7477_memtx_hash_idx_gt_iter_dirty_reads_test.lua
Labels: bug, memtx, teamC, mvcc, full-ci

#7410 memtx: fix reverse iterators gap tracking
  changelogs/unreleased/gh-4709-rev-iters-phantom-reads.md
  src/box/memtx_tree.cc
  src/box/memtx_tx.c
  test/box-luatest/gh_7409_rev_iters_phantom_reads_test.lua
Labels: bug, memtx, teamC, mvcc, full-ci

#7514 raft: make followers notice leader hang
  changelogs/unreleased/gh-7512-raft-leader-hang.md
  src/box/relay.cc
  test/replication-luatest/gh_7512_raft_leader_hang_test.lua
Labels: full-ci

#7538 ci: disable LuaJIT tests for OSX arm64 builds
  .test.mk
Labels: full-ci

#7444 memtx: fix tree iterator `next` result clarification
  changelogs/unreleased/gh-7432-fix-iter-next-clarify-after-track-gap.md
  src/box/memtx_tree.cc
  test/box-luatest/gh_7432_fix_iter_next_clarify_after_gap_track_test.lua
Labels: bug, memtx, teamC, mvcc, full-ci

#7541 memtx: fix dirty data written to snapshot for hash index
  changelogs/unreleased/gh-7539-mvcc-dirty-data-written-to-snapshot.md
  src/box/memtx_hash.cc
  test/box-luatest/gh_7539_mvcc_dirty_data_written_to_snapshot_test.lua
Labels: full-ci

#7532 cmake: show ENABLE_FEEDBACK_DAEMON in cmake output
  CMakeLists.txt
Labels: code health, full-ci

#7533 feedback: hide from box.cfg if disabled at build
  src/box/lua/load_cfg.lua
Labels: code health, full-ci

#7553 ci: fix version in GH action used for publishing
  .github/workflows/publish-module-api-doc.yaml
Labels: do not merge

#7544 ci: replace telegram notify with vk teams notify
  .github/actions/report-job-status/README.md
  .github/actions/report-job-status/action.yml
  .github/actions/send-telegram-notify/README.md
  .github/actions/send-telegram-notify/action.yml
  .github/workflows/centos_7.yml
  .github/workflows/centos_7_aarch64.yml
  .github/workflows/centos_8.yml
  .github/workflows/centos_8_aarch64.yml
  .github/workflows/coverage.yml
  .github/workflows/coverity.yml
  .github/workflows/debian_10.yml
  .github/workflows/debian_10_aarch64.yml
  .github/workflows/debian_11.yml
  .github/workflows/debian_11_aarch64.yml
  .github/workflows/debian_9.yml
  .github/workflows/debug.yml
  .github/workflows/debug_aarch64.yml
  .github/workflows/default_gcc_centos_7.yml
  .github/workflows/fedora_34.yml
  .github/workflows/fedora_34_aarch64.yml
  .github/workflows/fedora_35.yml
  .github/workflows/fedora_35_aarch64.yml
  .github/workflows/fedora_36.yml
  .github/workflows/fedora_36_aarch64.yml
  .github/workflows/freebsd-12.yml
  .github/workflows/freebsd-13.yml
  .github/workflows/fuzzing.yml
  .github/workflows/jepsen-cluster-txm.yml
  .github/workflows/jepsen-cluster.yml
  .github/workflows/jepsen-single-instance-txm.yml
  .github/workflows/jepsen-single-instance.yml
  .github/workflows/lint.yml
  .github/workflows/memtx_allocator_based_on_malloc.yml
  .github/workflows/opensuse_15_1.yml
  .github/workflows/opensuse_15_2.yml
  .github/workflows/osx_11.yml
  .github/workflows/osx_11_aarch64.yml
  .github/workflows/osx_11_aarch64_debug.yml
  .github/workflows/osx_11_lto.yml
  .github/workflows/osx_12.yml
  .github/workflows/osx_12_static_cmake.yml
  .github/workflows/out_of_source.yml
  .github/workflows/publish-module-api-doc.yaml
  .github/workflows/release.yml
  .github/workflows/release_asan_clang11.yml
  .github/workflows/release_clang.yml
  .github/workflows/release_lto.yml
  .github/workflows/release_lto_clang11.yml
  .github/workflows/source.yml
  .github/workflows/static_build.yml
  .github/workflows/static_build_cmake_linux.yml
  .github/workflows/submodule_update.yml
  .github/workflows/ubuntu_16_04.yml
  .github/workflows/ubuntu_18_04.yml
  .github/workflows/ubuntu_20_04.yml
  .github/workflows/ubuntu_20_04_aarch64.yml
  .github/workflows/ubuntu_22_04.yml
  .github/workflows/ubuntu_22_04_aarch64.yml
Labels: teamX

#7548 index: refactor snapshot iterator API
  src/box/index.cc
  src/box/index.h
  src/box/memtx_bitset.cc
  src/box/memtx_engine.cc
  src/box/memtx_hash.cc
  src/box/memtx_rtree.cc
  src/box/memtx_space.c
  src/box/memtx_tree.cc
  src/box/sequence.c
  src/box/sequence.h
  src/box/session_settings.c
  src/box/sysview.c
  src/box/vinyl.c
Labels: full-ci

#7508 ci: add workaround for LuaJit profiling tests
  .github/actions/environment/action.yml
Labels: 3sp, teamX, unplanned

#7555 console: remove ERRINJ_STDIN_ISATTY injection
  src/lib/core/errinj.h
  src/lua/init.c
  test/app-tap/gh-2717-no-quit-sigint.test.lua
  test/app-tap/gh-5040-inter-mode-isatty.test.lua
  test/box/errinj.result
Labels: full-ci

#7575 cmake: detect changes in source files upon static build
  static-build/CMakeLists.txt
Labels: full-ci

#7427 Gh 4450 logger sigsegv 3
  changelogs/unreleased/gh-4450-logger-sigsegv.md
  src/lib/core/say.c
  src/main.cc
  test/app-tap/gh-4450-log-rotate-exit.test.lua
  test/app-tap/suite.ini
Labels: full-ci

#7576 replication: fix downstream lag growing when there's no new transactions
  changelogs/unreleased/gh-7581-downstream-lag-calculation-fix.md
  src/box/relay.cc
  test/replication-luatest/gh_7581_downstream_lag_test.lua
Labels: full-ci

#7567 Introduce internal database read view API
  src/box/CMakeLists.txt
  src/box/blackhole.c
  src/box/engine.c
  src/box/engine.h
  src/box/memtx_engine.cc
  src/box/read_view.c
  src/box/read_view.h
  src/box/service_engine.c
  src/box/sysview.c
  src/box/vinyl.c
Labels: full-ci

#7551 test: fix flakiness in app-luatest/http_client_test.lua
  test/app-luatest/http_client_test.lua
  test/app-luatest/httpd.py
  test/app-luatest/suite.ini
  test/app-tap/suite.ini
  test/box-tap/suite.ini
Labels: full-ci

#7525 console: fix multiline commands saved as oneline
  changelogs/unreleased/gh-7320-restore-multiline-history.md
  src/box/lua/console.c
Labels: full-ci

#7597 memtx: fix tuple garbage collection not resumed after snapshot
  src/box/read_view.c
  test/box-luatest/memtx_gc_after_snapshot_test.lua
Labels: full-ci

#7610 Fix a bug in qsort
  changelogs/unreleased/gh-7605-fix-qsort.md
  test/box-luatest/gh_7605_qsort_recovery_test.lua
  test/box-luatest/suite.ini
  test/unit/CMakeLists.txt
  test/unit/qsort_arg.cc
  test/unit/qsort_arg.result
  third_party/qsort_arg_mt.c
Labels: full-ci, 2.10

#7607 ci: use `ubuntu-latest` instead of `ubuntu-18.04`
  .github/workflows/coverity.yml
  .github/workflows/fuzzing.yml
  .github/workflows/jepsen-cluster-txm.yml
  .github/workflows/jepsen-cluster.yml
  .github/workflows/jepsen-single-instance-txm.yml
  .github/workflows/jepsen-single-instance.yml
Labels: 1sp, teamX, full-ci, unplanned

#7616 ci: make module.h generation command more specific
  .github/workflows/publish-module-api-doc.yaml
Labels: full-ci
