Repository tarantool/tarantool, pull requests merged in 2022-06, with the labels that each got.

#7186 build: define TZDIR for tzcode build
  src/lib/tzcode/CMakeLists.txt
Labels: full-ci

#7229 net.box: fix hang in graceful shutdown protocol
  changelogs/unreleased/gh-7225-net-box-graceful-shutdown-hang.md
  src/box/lua/net_box.lua
  test/box-luatest/graceful_shutdown_test.lua
  test/box-luatest/net_box_test.lua
Labels: full-ci

#7246 test: use unix sockets in replication-py tests
  test/replication-py/suite.ini
  test/swim/suite.ini
Labels: full-ci

#7153 sql: fix wrong ephemeral space format
  changelogs/unreleased/gh-7043-ephem-space-format.md
  src/box/sql/select.c
  test/sql-luatest/gh_7043_temp_space_format_test.lua
Labels: full-ci

#7267 test: fix flaky viny/tx_gap_lock test
  test/vinyl/tx_gap_lock.result
  test/vinyl/tx_gap_lock.test.lua
Labels: full-ci

#7252 box: fix transaction "read-view" and "conflicted" states
  changelogs/unreleased/gh-7238-fix-conflicted-txs-in-memtx-ro-operations.md
  changelogs/unreleased/gh-7240-conflicted-transactions-error-on-all-crud-operations.md
  src/box/txn.c
  src/box/txn.h
  src/box/vy_tx.c
  test/box-luatest/gh_6246_mvcc_different_select_behavior_test.lua
  test/box-luatest/gh_6930_mvcc_isolation_levels_test.lua
  test/box-luatest/gh_6930_mvcc_net_box_iso_test.lua
  test/box-luatest/gh_7025_mvcc_dirty_range_test.lua
  test/box/tx_man.result
  test/engine-luatest/gh_7238_memtx_fix_conflicted_txs_ro_operations_test.lua
  test/engine-luatest/gh_7239_rv_txs_conflict_on_dml_test.lua
  test/vinyl/deferred_delete.result
  test/vinyl/hermitage.result
  test/vinyl/iterator.result
Labels: bug, vinyl, memtx, teamC, mvcc, full-ci

#7269 fiber: don't crash on wakeup with dead fibers
  changelogs/unreleased/gh-5843-fiber-wakeup.md
  src/lib/core/fiber.c
  test/unit/fiber.cc
  test/unit/fiber.result
Labels: full-ci

#7280 vinyl: fix `!vy_tx_is_in_read_view` assertion failure in `vy_tx_prepare`
  src/box/vy_tx.c
  test/vinyl-luatest/gh_7240_abort_yielding_dml_test.lua
Labels: full-ci

#7276 ci: add workflow for LuaJIT integration tests
  .github/workflows/luajit-integration.yml
  .travis.mk
Labels: full-ci

#7293 net.box: explicitly forbid synchronous requests in triggers
  changelogs/unreleased/gh-5358-net-box-sync-request-in-trigger.md
  src/box/lua/net_box.c
  src/box/lua/net_box.lua
  test/box-luatest/net_box_test.lua
Labels: full-ci

#7307 datetime: fix for setting when `hour=nil`
  changelogs/unreleased/gh-7298-datetime-set-with-hour-nil.md
  src/lua/datetime.lua
  test/app-tap/datetime.test.lua
Labels: 1sp, teamL, full-ci

#7260 tuple: refactor flags
  perf/tuple.cc
  src/box/memtx_tx.c
  src/box/memtx_tx.h
  src/box/tuple.c
  src/box/tuple.h
Labels: refactoring, full-ci

#7314 vinyl: disable deferred deletes if there are upserts on disk
  changelogs/unreleased/gh-3638-vy-defer-deletes-and-upserts.md
  src/box/vinyl.c
  test/vinyl-luatest/gh_3638_defer_deletes_and_upserts_test.lua
Labels: full-ci

#6752 test: box_promote and box_demote
  src/box/raft.c
  src/lib/core/errinj.h
  test/box/errinj.result
  test/replication-luatest/gh_6033_box_promote_demote_test.lua
  test/replication-luatest/suite.ini
Labels: full-ci

#7306 gcov: use __gcov_dump + __gcov_reset instead of __gcov_flush
  cmake/profile.cmake
  src/main.cc
  src/trivia/util.h
Labels: full-ci
