Repository tarantool/tarantool, pull requests merged in 2022-02, with the labels that each got.

#6810 ci: split debug_coverage.yml into two workflows
  .github/workflows/coverage.yml
  .github/workflows/debug.yml
  .github/workflows/debug_coverage.yml
  .travis.mk
Labels: full-ci

#6788 memtx: fix MVCC breaking TREE index iterators
  changelogs/unreleased/gh_6344_mvcc_txm_story_gc_breaks_memtx_tree_iter.md
  src/box/memtx_tree.cc
  test/box-luatest/gh_6344_mvcc_txm_story_gc_breaks_memtx_tree_iter_test.lua
Labels: bug, complicated, critical, memtx, teamC, mvcc, full-ci

#6836 console: fix memory leak
  changelogs/unreleased/gh-6817-console-memory-leak.md
  src/box/lua/console.c
  test/app-luatest/gh_6817_console_memory_leak_test.lua
Labels: full-ci

#6571 box: role 'public' rw access on _session_settings
  changelogs/unreleased/gh-6310-grant-rw-access-on-_session_settings-space-to-public-role.md
  src/box/bootstrap.snap
  src/box/lua/upgrade.lua
  test/box-luatest/gh_6310_grant_rw_access_on__session_settings_space_to_public_role_test.lua
  test/box-luatest/upgrade/2.9.1/00000000000000000000.snap
  test/box-luatest/upgrade/2.9.1/00000000000000000000.xlog
  test/box-py/bootstrap.result
  test/box/access_sysview.result
Labels: full-ci

#6828 core: refactor `get_proc_name`
  src/lib/core/backtrace.cc
Labels: teamC

#6557 Migrate update_optimize.test.lua to luatest
  test/vinyl-luatest/common.lua
  test/vinyl-luatest/update_optimize_test.lua
  test/vinyl/update_optimize.result
  test/vinyl/update_optimize.test.lua
Labels: full-ci

#6826 netbox: allow to disable schema fetch
  changelogs/unreleased/gh-4789-net-box-fetch-schema.md
  src/box/lua/net_box.c
  src/box/lua/net_box.lua
  test/box-luatest/net_box_test.lua
Labels: full-ci

#6866 test: remove checksums from suite.ini config files
  test/app-tap/suite.ini
  test/app/suite.ini
  test/box-py/suite.ini
  test/box-tap/suite.ini
  test/box/suite.ini
  test/engine/suite.ini
  test/engine_long/suite.ini
  test/replication-py/suite.ini
  test/replication/suite.ini
  test/sql-tap/suite.ini
  test/sql/suite.ini
  test/swim/suite.ini
  test/vinyl/suite.ini
  test/wal_off/suite.ini
  test/xlog/suite.ini
Labels: full-ci

#6871 Move OpenSSL initialization to lib/core/ssl
  src/CMakeLists.txt
  src/lib/core/CMakeLists.txt
  src/lib/core/ssl.c
  src/lib/core/ssl.h
  src/lib/crypto/crypto.c
  src/lib/crypto/crypto.h
  src/main.cc
  test/unit/CMakeLists.txt
  test/unit/crypto.c
Labels: full-ci

#6867 sql: allow LIMIT with different sorting order
  changelogs/unreleased/gh-6664-limit-in-oder-by.md
  src/box/sql/expr.c
  src/box/sql/parse.y
  src/box/sql/select.c
  src/box/sql/sqlInt.h
  test/sql-luatest/gh_6664_allow_limit_in_order_by_test.lua
  test/sql-luatest/suite.ini
  test/sql-tap/orderby8.test.lua
Labels: full-ci

#6872 vinyl: fix crash during secondary index recovery
  changelogs/unreleased/gh-6778-vinyl-recovery-crash.md
  src/box/vinyl.c
  test/vinyl-luatest/gh_6778_recovery_crash_test.lua
Labels: full-ci

#6874 module api/doc: bless box region as a fiber region
  src/lib/core/fiber.h
Labels: documentation
