Repository tarantool/tarantool, pull requests merged in 2022-09, with the labels that each got.

#7631 Generate changelog for 2.10.2
  changelogs/2.10.2.md
  changelogs/unreleased/gh-4264-trigger-crash-on-nontrivial-change.md
  changelogs/unreleased/gh-4450-logger-sigsegv.md
  changelogs/unreleased/gh-7320-restore-multiline-history.md
  changelogs/unreleased/gh-7473-system-fibers.md
  changelogs/unreleased/gh-7489-concurrent-fiber-join.md
  changelogs/unreleased/gh-7581-downstream-lag-calculation-fix.md
  changelogs/unreleased/gh-7605-fix-qsort.md
  changelogs/unreleased/gh-7614-fix-nullable-from-format.md
  changelogs/unreleased/ghs-5-fix-auth-check-on-truncate.md
Labels: full-ci

#7441 memtx: tuple read view improvements
  src/box/memtx_allocator.cc
  src/box/memtx_allocator.h
  test/unit/memtx_allocator.cc
  test/unit/memtx_allocator.result
Labels: full-ci

#7626 test: always perform assertions in module API test
  test/app-tap/module_api.c
Labels: full-ci

#7542 tarantoolctl: fix default host for connect
  changelogs/unreleased/igrishnov/gh-7479-bug-fix-uri-lib.md
  src/box/lua/net_box.lua
  src/lib/uri/uri.c
  test/app-luatest/gh_7479_bug_fix_uri_lib_test.lua
  test/app-tap/uri.test.lua
Labels: full-ci

#7641 sql: fix drop of constraints during ADD COLUMN
  src/box/sql.c
  test/sql-luatest/constraint_test.lua
Labels: full-ci

#7606 Add build RedOS linux package
  .github/workflows/redos_7_3.yaml
  changelogs/unreleased/add-redos-7.3-ci-cd.md
Labels: full-ci

#7649 popen: fix a race between setpgrp() and killpg()
  changelogs/unreleased/popen-mac-os-race.md
  src/lib/core/popen.c
  src/lua/popen.c
  test/app-tap/popen.skipcond
Labels: full-ci

#7663 Use MT-Safe `strerror_r` instead of `strerror`
  CMakeLists.txt
  changelogs/unreleased/strerror-mt-safe.md
  extra/exports
  src/box/lua/info.c
  src/lib/core/CMakeLists.txt
  src/lib/core/backtrace.c
  src/lib/core/crash.c
  src/lib/core/evio.c
  src/lib/core/exception.cc
  src/lib/core/say.c
  src/lib/core/say.h
  src/lib/core/tt_strerror.c
  src/lib/core/tt_strerror.h
  src/lua/errno.lua
  src/main.cc
  src/module_header.h
  src/trivia/config.h.cmake
  test/unit/say.c
Labels: full-ci

#7661 read_view: add option to include temporary spaces
  src/box/engine.c
  src/box/engine.h
  src/box/memtx_engine.cc
  src/box/read_view.c
  src/box/read_view.h
Labels: full-ci

#7439 ffi(fiber): add fiber_set_arg & fiber_get_arg functions to enable cus…
  changelogs/unreleased/add-fiber_set_ctx.md
  extra/exports
  src/lib/core/fiber.c
  src/lib/core/fiber.h
  test/app-tap/module_api.c
  test/app-tap/module_api.test.lua
Labels: full-ci

#7543 memtx: track read story in when conflicting full scans due to gap write
  changelogs/unreleased/gh-7493-memtx-hash-idx-repeatable-read-violation.md
  src/box/memtx_tx.c
  test/box-luatest/gh_7493_memtx_hash_idx_repeatable_read_violation_test.lua
Labels: bug, memtx, teamC, mvcc, full-ci

#7664 lua/merger: fix use-after-free during iteration
  changelogs/unreleased/merger-use-after-free-in-gen.md
  src/box/lua/merger.c
  test/box-luatest/gh_7657_merger_use_after_free_in_gen_test.lua
Labels: full-ci

#7466 memtx: fix 'use after free' of garbage collected MVCC stories
  changelogs/unreleased/gh-7449-tuple-is-dirty-assertion-on-replace.md
  src/box/memtx_bitset.cc
  src/box/memtx_hash.cc
  src/box/memtx_rtree.cc
  src/box/memtx_tree.cc
  src/box/memtx_tx.c
  src/box/memtx_tx.h
  test/box-luatest/gh_7449_tuple_is_dirty_assertion_on_replace_test.lua
Labels: bug, complicated, memtx, teamC, mvcc, full-ci

#7673 test: make exit code depends on checking test plan
  test/app-tap/cfg.test.lua
  test/app-tap/console.test.lua
  test/app-tap/csv.test.lua
  test/app-tap/errno.test.lua
  test/app-tap/fail_main.test.lua
  test/app-tap/func.test.lua
  test/app-tap/info.test.lua
  test/app-tap/json.test.lua
  test/app-tap/logmod.test.lua
  test/app-tap/minimal.test.lua
  test/app-tap/msgpack.test.lua
  test/app-tap/msgpackffi.test.lua
  test/app-tap/snapshot.test.lua
  test/app-tap/uri.test.lua
  test/app-tap/yaml.test.lua
  test/box-tap/cfg.test.lua
  test/box-tap/cfgup.test.lua
  test/box-tap/feedback_daemon.test.lua
  test/box-tap/gc.test.lua
  test/box-tap/gh-5750-feedback-disabled-err.test.lua
  test/box-tap/net.box.test.lua
  test/box-tap/on_schema_init.test.lua
  test/box-tap/schema_mt.test.lua
  test/box-tap/session.storage.test.lua
  test/sql-tap/lua/sqltester.lua
Labels: full-ci

#7587 cmake: add extra security compiler options
  CMakeLists.txt
  changelogs/unreleased/gh-7536-add-cmake-enable_hardening-option.md
  cmake/BuildAres.cmake
  cmake/BuildLibCURL.cmake
  cmake/BuildLibUnwind.cmake
  cmake/BuildNghttp2.cmake
  debian/rules
  rpm/tarantool.spec
  static-build/CMakeLists.txt
Labels: full-ci

#7517 box: check constraint name against identifier rules
  src/box/tuple_constraint_def.c
  test/engine-luatest/gh_6436_complex_foreign_key_test.lua
  test/engine-luatest/gh_6436_field_constraint_test.lua
  test/engine-luatest/gh_6436_field_foreign_key_test.lua
  test/engine-luatest/gh_6436_tuple_constraint_test.lua
Labels: full-ci

#7683 memtx: track `index:random` reads and clarify result
  changelogs/unreleased/gh-7670-memtx-tx-manager-idx-rand-inconsistency.md
  src/box/memtx_hash.cc
  src/box/memtx_tree.cc
  test/box-luatest/gh_7670_memtx_tx_manager_idx_rand_inconsistency_test.lua
  test/box-luatest/suite.ini
Labels: bug, memtx, teamC, mvcc, full-ci

#7706 xrow: fix crash on nested map/array update ops
  changelogs/unreleased/gh-7705-json-update-crash.md
  src/box/xrow_update_route.c
  test/box/update.result
  test/box/update.test.lua
Labels: full-ci

#7707 test: replace Lua assertions with luatest assertions in luatest tests
  test/app-luatest/gh_6817_console_memory_leak_test.lua
  test/app-luatest/gh_7288_console_flavours_vs_txn_test.lua
  test/app-luatest/http_client_test.lua
  test/app-luatest/http_client_unit_test.lua
  test/box-luatest/gh_6150_memtx_tx_memory_monitoring_test.lua
  test/box-luatest/gh_6260_add_builtin_events_test.lua
  test/replication-luatest/election_split_vote_test.lua
  test/replication-luatest/gh_5295_split_brain_test.lua
  test/replication-luatest/gh_5568_read_only_reason_test.lua
Labels: full-ci

#7711 box: support module as unit of reconfiguring
  src/box/lua/load_cfg.lua
Labels: full-ci

#7732 box: fix typo in 2.11.0-entrypoint-501-gdfa1142cf
  src/box/lua/load_cfg.lua
  test/box-luatest/error_on_dynamic_cfg_in_load_cfg_test.lua
Labels: full-ci

#7734 gc: replace vclockset_psearch with _match in wal_collect_garbage_f
  changelogs/unreleased/gh-7584-missing-xlog-fix.md
  src/box/wal.c
  src/lib/vclock/vclock.h
  test/replication-luatest/gh_7584_missing_xlog_test.lua
Labels: full-ci

#7740 vinyl: implement iterator pagination
  src/box/vinyl.c
  src/box/vy_read_iterator.c
  src/box/vy_read_iterator.h
  test/engine-luatest/pagination_test.lua
Labels: full-ci

#7744 box: fix usage of pcall/box.error idiom
  src/box/lua/load_cfg.lua
  src/box/lua/net_box.lua
Labels: full-ci

#7717 memtx: fix loss of committed tuple in secondary index
  changelogs/unreleased/gh-7712-loss-of-commited-tuple-in-secondary-index.md
  src/box/memtx_tx.c
  test/box-luatest/gh_7712_loss_of_commited_tuple_in_secondary_index_test.lua
Labels: full-ci

#7742 box: fix usage error messages if FFI is disabled for index read ops
  src/box/lua/index.c
  src/box/lua/schema.lua
  test/box-luatest/box_read_ffi_disable_test.lua
Labels: full-ci

#7751 test: don't call box.cfg() from test instance in gh-7288
  test/app-luatest/gh_7288_console_flavours_vs_txn_test.lua
  test/app-luatest/gh_7288_console_helper.lua
Labels: full-ci
