Repository tarantool/tarantool, pull requests merged in 2022-07, with the labels that each got.

#7332 json: don't match any nodes if there's [*] in the path
  changelogs/unreleased/gh-5226-tuple-access-by-any-token.md
  src/lib/json/json.h
  test/box-luatest/gh_5226_tuple_access_by_any_token_test.lua
  test/unit/json.c
Labels: full-ci

#7352 test: add improved test for SELECT consistency
  test/vinyl-luatest/select_consistency_test.lua
  test/vinyl-luatest/suite.ini
Labels: full-ci

#7359 test: stop server started by `vinyl-luatest/update_optimize` test
  test/vinyl-luatest/update_optimize_test.lua
Labels: full-ci

#7215 memtx: fix story delete statement list
  changelogs/unreleased/gh-7214-repeatable-replace-assertion.md
  changelogs/unreleased/gh-7217-repeatable-{in, up}sert-memtx-tx-conflict.md
  src/box/memtx_tx.c
  src/box/txn.c
  src/box/txn.h
  test/box-luatest/gh_7214_repeatable_replace_assertion_test.lua
  test/box-luatest/gh_7217_repeatable_{in, up}sert_memtx_tx_conflict_test.lua
Labels: bug, complicated, memtx, teamC, mvcc, full-ci

#7335 test: use default readline configuration for a test
  test/app-tap/gh-2717-no-quit-sigint.test.lua
Labels: full-ci

#7367 ci: install test-run deps via pip instead of apt
  .travis.mk
Labels: full-ci

#7377 ci: add autoconf and automake deps to make targets
  .travis.mk
Labels: full-ci

#7349 sql: ariphmetic of unsigned values
  changelogs/unreleased/gh-7295-unit-arith-res-type.md
  src/box/sql/expr.c
  test/sql-luatest/gh_7295_uint_and_int_def_err_test.lua
Labels: full-ci

#7353 sql: fix error in ORDER BY ephemeral space format
  changelogs/unreleased/gh-7345-any-in-order-by-ephem.md
  src/box/sql/select.c
  test/sql-luatest/gh_7345_any_in_order_by_ephem_test.lua
Labels: full-ci

#7379 ci: fix deps installation for FreeBSD systems
  .travis.mk
Labels: full-ci

#7315 box: fix unexpected error on granting privileges to admin
  changelogs/unreleased/gh-7226-admin-grant-error.md
  src/box/lua/schema.lua
  test/box-luatest/gh_7226_admin_grant_error_test.lua
Labels: full-ci

#7382 test: fix cleanup in `vinyl-luatest/gh_6565_hot_standby_unsupported` test
  test/vinyl-luatest/gh_6565_hot_standby_unsupported_test.lua
Labels: full-ci

#7378 build: fix error on FreeBSD 13.1
  test/unit/CMakeLists.txt
Labels: full-ci

#7391 build: satisfy -Wunused-but-set-variable check
  src/box/tuple_update.c
Labels: build, bug

#7383 http client: return back CA certificates search
  changelogs/unreleased/add-https-certificate-validation-back.md
  cmake/BuildLibCURL.cmake
Labels: full-ci

#7397 box: fix finding snapshot in upgrade script
  changelogs/unreleased/gh-7232-upgrade-script-work-dir.md
  src/box/lua/load_cfg.lua
  test/xlog/gh-5894-pre-1.7.7-upgrade.result
  test/xlog/gh-5894-pre-1.7.7-upgrade.test.lua
  test/xlog/upgrade.lua
Labels: full-ci

#7417 static-build: bump openssl from 1.1.1n to 1.1.1q
  changelogs/unreleased/bump-openssl-to-111q.md
  static-build/CMakeLists.txt
  static-build/openssl-111q-gh-18720.patch
Labels: security, full-ci

#7251 lua: fix sigint behavior in multiline input mode
  changelogs/unreleased/gh-7109-fix-ctrl-c-in-multiline-input-mode.md
  src/box/lua/console.c
  src/box/lua/console.lua
  test/app-tap/gh-2717-no-quit-sigint.test.lua
Labels: full-ci

#7453 test: fix execpl call in unit/coio test
  test/unit/coio.cc
Labels: full-ci

#7360 box: use 0 as a space id for FK that refer to the same space
  changelogs/unreleased/gh-7200-use-0-as-space-id-for-self-fkey.md
  src/box/lua/schema.lua
  src/box/lua/space.cc
  src/box/tuple_constraint_def.c
  src/box/tuple_constraint_fkey.c
  test/engine-luatest/gh_6436_field_foreign_key_test.lua
  test/engine-luatest/gh_7200_fkey_without_space_id_test.lua
Labels: full-ci

#7476 ci: call reusable_build.yml from 1.10 branch
  .github/workflows/integration.yml
Labels: integration-ci

#7474 box: check for foreign keys on space:truncate()
  changelogs/unreleased/gh-7309-check-fkey-on-truncate.md
  src/box/alter.cc
  test/engine-luatest/gh_7309_check_fkey_on_truncate_test.lua
Labels: full-ci

#7481 ci: make LuaJIT integration workflow rerunnable
  .github/workflows/luajit-integration.yml
Labels: full-ci

#7482 box: fix `thread_id` check in `box.stat.net.thread[]`
  changelogs/unreleased/gh-7196-fix-box-stat-net-thread.md
  src/box/lua/stat.c
  test/box/gh-6293-implement-new-net-stat.result
  test/box/gh-6293-implement-new-net-stat.test.lua
Labels: full-ci
