Repository tarantool/tarantool, pull requests merged in 2022-04, with the labels that each got.

#6977 replication: fix bootstrap failing with ER_READONLY
  changelogs/unreleased/gh-6966-readonly-bootstrap.md
  src/box/applier.cc
  src/box/box.cc
  test/replication-luatest/gh_6966_readonly_bootstrap_test.lua
  test/replication-py/cluster.test.py
  test/replication-py/init_storage.skipcond
  test/replication/gh-5613-bootstrap-prefer-booted.result
  test/replication/gh-5613-bootstrap-prefer-booted.test.lua
  test/replication/suite.ini
Labels: full-ci

#6999 cmake: don't include EXTRA_CORE_INCLUDE_DIRS in test/CMakeLists.txt
  test/CMakeLists.txt
Labels: full-ci

#6967 app: fix crash with multiple -e -l options
  changelogs/unreleased/gh-5747-crash-multiple-args.md
  src/main.cc
  test/app-luatest/gh_5747_crash_multiple_args_test.lua
Labels: full-ci

#7010 tx: set session and user for commit/rollback triggers
  changelogs/unreleased/gh-7005-session-on-commit-rollback.md
  src/box/session.h
  src/box/txn.c
  test/box-luatest/gh_7005_session_on_commit_rollback_test.lua
  test/luatest_helpers/misc.lua
Labels: full-ci

#7021 ci: specify number of jobs when executing `make`
  .github/workflows/perf_sysbench.yml
  .travis.mk
Labels: full-ci

#7018 static-build: update libicu version
  changelogs/unreleased/update-libicu-static-build.md
  static-build/CMakeLists.txt
Labels: full-ci

#6983 tarantoolctl: fix command in help messages
  changelogs/unreleased/gh-6983-fix-command-in-help-messages.md
  extra/dist/tarantoolctl.in
  test/app-tap/tarantoolctl.test.lua
Labels: full-ci

#6971 core: partitioned ring buffer
  src/lib/core/CMakeLists.txt
  src/lib/core/prbuf.c
  src/lib/core/prbuf.h
  test/unit/CMakeLists.txt
  test/unit/prbuf.c
  test/unit/prbuf.result
Labels: full-ci

#7022 lua: introduce interface for prbuf
  extra/exports
  src/lua/buffer.lua
  test/app-luatest/prbuf_test.lua
Labels: full-ci

#7034 static-build: bump openssl from 1.1.1f to 1.1.1n
  changelogs/unreleased/bump-openssl-to-111n.md
  static-build/CMakeLists.txt
Labels: full-ci

#7016 Fix box.session.peer in box.session.on_disconnect triggers
  changelogs/unreleased/gh-7014-session-disconnect-peer.md
  src/box/iproto.cc
  src/box/lua/session.c
  src/box/session.cc
  src/box/session.h
  test/box-luatest/gh_7014_session_disconnect_peer_test.lua
  test/box-tap/session.test.lua
Labels: full-ci

#7028 lua: track memory occupied by runtime tuples
  changelogs/unreleased/box-runtime-info-tuple.md
  src/box/lua/slab.cc
  src/box/tuple.c
  src/box/tuple.h
  test/box-luatest/box_runtime_info_tuple_test.lua
Labels: full-ci

#7009 raft: send promote only after new term has been broadcasted
  changelogs/unreleased/gh-6754-term-bump-before-promote.md
  src/box/lua/info.c
  src/box/relay.cc
  src/lib/core/errinj.h
  test/box/errinj.result
  test/luatest_helpers/server.lua
  test/replication-luatest/gh_6754_promote_before_new_term_test.lua
Labels: full-ci

#7057 sql: fixes for new built-in functions
  src/lib/core/datetime.c
  test/fuzz/datetime_parse_full_fuzzer.c
  test/fuzz/datetime_strptime_fuzzer.c
  test/sql-luatest/datetime_test.lua
Labels: full-ci

#7047 box: fix problem with SCALAR and UUID
  src/box/field_def.c
  test/box-luatest/gh_6042_uuid_and_scalar_test.lua
Labels: full-ci

#7055 mvcc: track nothing-found range read
  changelogs/unreleased/gh-7025-mvcc-dirty-range.md
  src/box/memtx_tree.cc
  test/box-luatest/gh_7025_mvcc_dirty_range_test.lua
Labels: full-ci

#6981 raft: implement leader fencing
  changelogs/unreleased/elections-leader-fencing.md
  src/box/box.cc
  src/box/box.h
  src/box/lua/cfg.cc
  src/box/lua/load_cfg.lua
  src/box/raft.c
  src/box/raft.h
  src/box/txn_limbo.c
  src/box/txn_limbo.h
  src/lib/raft/raft.c
  src/lib/raft/raft.h
  test/app-tap/init_script.result
  test/box/admin.result
  test/box/cfg.result
  test/replication-luatest/election_fencing_test.lua
  test/replication/election_replica.lua
  test/unit/raft.c
  test/unit/raft.result
  test/unit/raft_test_utils.c
  test/unit/raft_test_utils.h
Labels: full-ci

#7053 box: fix complex foreign keys with nullable fields
  changelogs/unreleased/gh-7046-fix-nullable-complex-fkeys.md
  src/box/tuple_constraint_fkey.c
  test/engine-luatest/gh_7046_complex_fkey_nullable_test.lua
Labels: full-ci

#5989 Changed signedness of time64 functions from uint64_t to int64_t
  changelogs/unreleased/changed-signedness-of-time64-functions.md
  src/lib/core/clock.c
  src/lib/core/clock.h
  src/lib/core/fiber.c
  src/lib/core/fiber.h
  src/lua/clock.lua
  src/lua/fiber.lua
  test/app-tap/clock.test.lua
Labels: teamE, full-ci

#7067 sql: fix string dequoting
  changelogs/unreleased/fix-string-dequoting.md
  src/box/sql/util.c
  test/sql-luatest/gh_7063_dequote_test.lua
Labels: full-ci

#7068 build: clang fails because of -Wnull-pointer-subtraction
  src/box/sql/sqlInt.h
Labels: bug, sql, teamL, full-ci
