Repository tarantool/tarantool, pull requests merged in 2022-12, with the labels that each got.

#7975 backtrace: update `sp` before saving registers to a stack frame
  changelogs/unreleased/gh-7523-sigsegv-on-m1-macs.md
  src/lib/core/backtrace.c
Labels: full-ci

#7997 cmake: fix wrong CPU architecture reported on M1/M2 Macs
  changelogs/unreleased/gh-7495-wrong-arch-reported-on-m1-macs.md
  cmake/arch.cmake
  test/app-luatest/gh_7495_tarantool_build_target_test.lua
Labels: full-ci

#7957 msgpack: add `__index` metamethod and `get` method to `msgpack.object`
  changelogs/unreleased/gh-7898-msgpack-object-indexation.md
  src/lua/msgpack.c
  test/app-luatest/msgpack_test.lua
Labels: full-ci

#8001 box: export current session's identifier to C API
  changelogs/unreleased/gh-7895-export-session-id-to-c-api.md
  extra/exports
  src/box/box.cc
  src/box/box.h
  src/box/lua/session.c
  test/app-tap/module_api.c
  test/app-tap/module_api.test.lua
Labels: full-ci

#8004 zlib CE part
  CMakeLists.txt
Labels: full-ci

#8000 ci: prepare workspace before actions/checkout
  .github/workflows/centos_7.yml
  .github/workflows/centos_7_aarch64.yml
  .github/workflows/centos_8.yml
  .github/workflows/centos_8_aarch64.yml
  .github/workflows/codeql.yml
  .github/workflows/coverage.yml
  .github/workflows/coverity.yml
  .github/workflows/debian_10.yml
  .github/workflows/debian_10_aarch64.yml
  .github/workflows/debian_11.yml
  .github/workflows/debian_11_aarch64.yml
  .github/workflows/debian_9.yml
  .github/workflows/debug.yml
  .github/workflows/debug_aarch64.yml
  .github/workflows/default_gcc_centos_7.yml
  .github/workflows/fedora_34.yml
  .github/workflows/fedora_34_aarch64.yml
  .github/workflows/fedora_35.yml
  .github/workflows/fedora_35_aarch64.yml
  .github/workflows/fedora_36.yml
  .github/workflows/fedora_36_aarch64.yml
  .github/workflows/freebsd-12.yml
  .github/workflows/freebsd-13.yml
  .github/workflows/jepsen-cluster-txm.yml
  .github/workflows/jepsen-cluster.yml
  .github/workflows/jepsen-single-instance-txm.yml
  .github/workflows/jepsen-single-instance.yml
  .github/workflows/lint.yml
  .github/workflows/luajit-integration.yml
  .github/workflows/memtx_allocator_based_on_malloc.yml
  .github/workflows/osx_11.yml
  .github/workflows/osx_11_aarch64.yml
  .github/workflows/osx_11_aarch64_debug.yml
  .github/workflows/osx_11_lto.yml
  .github/workflows/osx_12.yml
  .github/workflows/osx_12_static_cmake.yml
  .github/workflows/out_of_source.yml
  .github/workflows/publish-module-api-doc.yaml
  .github/workflows/redos_7_3.yaml
  .github/workflows/release.yml
  .github/workflows/release_asan_clang11.yml
  .github/workflows/release_clang.yml
  .github/workflows/release_lto.yml
  .github/workflows/release_lto_clang11.yml
  .github/workflows/reusable_build.yml
  .github/workflows/source.yml
  .github/workflows/static_build.yml
  .github/workflows/static_build_cmake_linux.yml
  .github/workflows/ubuntu_16_04.yml
  .github/workflows/ubuntu_18_04.yml
  .github/workflows/ubuntu_20_04.yml
  .github/workflows/ubuntu_20_04_aarch64.yml
  .github/workflows/ubuntu_22_04.yml
  .github/workflows/ubuntu_22_04_aarch64.yml
Labels: full-ci

#8032 xrow: use `xregion_alloc` in encoders
  src/box/applier.cc
  src/box/box.cc
  src/box/memtx_engine.cc
  src/box/raft.c
  src/box/relay.cc
  src/box/request.c
  src/box/txn.c
  src/box/vy_log.c
  src/box/vy_stmt.c
  src/box/xlog.c
  src/box/xrow.c
  src/box/xrow.h
  src/box/xrow_io.cc
  test/unit/xrow.cc
Labels: full-ci

#6910 lua_cjson: fix encode() escaping slash
  changelogs/unreleased/gh-6200-lua_cjson-encode-escapes-slash.md
  src/lua/compat.c
  src/lua/compat.lua
  src/lua/serializer.c
  src/lua/serializer.h
  test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua
  third_party/lua-cjson/lua_cjson.c
Labels: full-ci

#7250 lua-yaml: improve multiline string output
  changelogs/unreleased/gh-3012-yaml-prettier-multiline-output
  src/lua/compat.c
  src/lua/compat.lua
  test/app-luatest/gh_3012_yaml_prettier_multiline_output_test.lua
  third_party/lua-yaml/lyaml.cc
  third_party/lua-yaml/lyaml.h
Labels: full-ci

#8040 cd: eliminate OpenSUSE related code from RPM spec
  rpm/tarantool.spec
Labels: full-ci

#8050 ci: use actions/checkout@v3.1.0 with FreeBSD
  .github/workflows/freebsd-12.yml
  .github/workflows/freebsd-13.yml
Labels: full-ci

#8059 log: call log_write_flightrec regardless of the log level
  extra/exports
  src/lib/core/say.c
  src/lua/log.lua
Labels: full-ci

#8061 Eliminate dependency of core lib headers on `libunwind.h`
  src/lib/core/backtrace.c
  src/lib/core/backtrace.h
  src/lib/core/proc_name_cache.cc
  src/lib/core/proc_name_cache.h
  src/lua/backtrace.c
  test/fuzz/CMakeLists.txt
  test/unit/CMakeLists.txt
Labels: full-ci

#8065 box: let authentication method require encryption
  src/box/applier.cc
  src/box/auth_chap_sha1.c
  src/box/authentication.c
  src/box/authentication.h
  src/box/lua/net_box.c
  src/lib/core/iostream.h
Labels: full-ci

#8048 lua: use cur_L in cord_on_yield
  changelogs/unreleased/gh-6647-yield-gc-hook.md
  src/lua/utils.c
  test/box-luatest/gh_6647_yield_gc_hook_test.lua
Labels: full-ci

#8080 test: do `jit.flush()` after `jit.off()` on arm64
  test/app-tap/datetime.test.lua
  test/box-luatest/gh_6539_log_user_space_empty_or_nil_select_test.lua
  test/box-luatest/pagination_netbox_test.lua
  test/engine-luatest/pagination_test.lua
Labels: full-ci

#7967 sql: refactor memory allocation system
  extra/lemon.c
  extra/lempar.c
  src/box/alter.cc
  src/box/ck_constraint.c
  src/box/lua/execute.c
  src/box/sql.c
  src/box/sql.h
  src/box/sql/alter.c
  src/box/sql/build.c
  src/box/sql/delete.c
  src/box/sql/expr.c
  src/box/sql/fk_constraint.c
  src/box/sql/func.c
  src/box/sql/hash.c
  src/box/sql/insert.c
  src/box/sql/main.c
  src/box/sql/malloc.c
  src/box/sql/mem.c
  src/box/sql/mem.h
  src/box/sql/os.c
  src/box/sql/os.h
  src/box/sql/os_unix.c
  src/box/sql/parse.y
  src/box/sql/parse_def.h
  src/box/sql/port.c
  src/box/sql/pragma.c
  src/box/sql/prepare.c
  src/box/sql/printf.c
  src/box/sql/resolve.c
  src/box/sql/select.c
  src/box/sql/sqlInt.h
  src/box/sql/tarantoolInt.h
  src/box/sql/tokenize.c
  src/box/sql/treeview.c
  src/box/sql/trigger.c
  src/box/sql/update.c
  src/box/sql/util.c
  src/box/sql/vdbe.c
  src/box/sql/vdbe.h
  src/box/sql/vdbeInt.h
  src/box/sql/vdbeapi.c
  src/box/sql/vdbeaux.c
  src/box/sql/vdbesort.c
  src/box/sql/vdbetrace.c
  src/box/sql/where.c
  src/box/sql/wherecode.c
  src/box/sql/whereexpr.c
Labels: full-ci

#8081 test: fix flaky 'sigterm during box.cfg' test
  test/box-luatest/gh_7743_term_initial_cfg_snap_test.lua
Labels: full-ci

#8060 ci: test stable branches with SDK
  .github/workflows/submodule_update.yml
Labels: notest

#8071 sql: correctly calculate argument types
  changelogs/unreleased/gh-7992-collation-of-built-in-args.md
  src/box/sql/func.c
  test/sql-luatest/gh_7992_update_collate_test.lua
Labels: full-ci

#8063 Don't replace `stdin` with `/dev/urandom` after fork
  changelogs/unreleased/gh-7886-dont-close-xlog-fd-atfork.md
  src/box/box.cc
  src/box/box.h
  src/box/wal.c
  src/box/wal.h
  src/box/xlog.c
  src/box/xlog.h
  src/main.cc
Labels: full-ci

#8067 core: drop constraints in two phases
  changelogs/unreleased/gh_7339_fk_drop_in_one_txn.md
  src/box/alter.cc
  src/box/space.c
  src/box/space.h
  src/box/tuple_constraint.c
  src/box/tuple_constraint.h
  src/box/tuple_constraint_fkey.c
  src/box/tuple_constraint_func.c
  test/engine-luatest/gh_7339_drop_fk_in_same_txn_test.lua
Labels: full-ci

#8093 test: stabilize jit.dump() smoke test
  test/app-tap/gh-5983-jit-library-smoke-tests.test.lua
Labels: full-ci

#7825 fiber: add channel graceful close option to compat
  changelogs/unreleased/gh-7746-fiber-channel-graceful-close.md
  src/lib/core/fiber_channel.c
  src/lib/core/fiber_channel.h
  src/lua/compat.c
  src/lua/compat.lua
  test/app-luatest/gh_7746_fiber_channel_close_test.lua
  test/unit/fiber_channel.cc
  test/unit/fiber_channel.result
Labels: full-ci

#8090 box: add stubs for extra authentication checks
  src/box/authentication.c
  src/box/box.cc
  src/box/errcode.h
  src/box/iproto.cc
  src/box/lua/load_cfg.lua
  src/box/security.h
  test/box/box.lua
  test/box/error.result
Labels: full-ci

#8101 sql: remove unused variables
  src/box/sql.c
  src/box/sql/build.c
  src/box/sql/expr.c
  src/box/sql/tarantoolInt.h
  src/box/sql/vdbe.c
  src/box/sql/vdbeaux.c
Labels: full-ci

#8056 ci: integration testing workflow for crud and ddl modules
  .github/workflows/integration.yml
Labels: integration-ci, notest

#8103 [2.10] ci: add integration testing for ddl and crud
  .github/workflows/integration.yml
Labels: integration-ci

#8106 ci: fix pull_request trigger for coverage workflow
  .github/workflows/coverage.yml
Labels: full-ci
