Repository tarantool/tarantool, pull requests merged in 2022-05, with the labels that each got.

#7094 ci: run integration WF on 'integration-ci' label
  .github/workflows/integration.yml
Labels: integration-ci

#7115 ci: follow-up improvements for gc64 builds
  .github/workflows/centos_7.yml
  .github/workflows/centos_8.yml
  .github/workflows/debian_10.yml
  .github/workflows/debian_11.yml
  .github/workflows/debian_9.yml
  .github/workflows/fedora_30.yml
  .github/workflows/fedora_31.yml
  .github/workflows/fedora_32.yml
  .github/workflows/fedora_33.yml
  .github/workflows/fedora_34.yml
  .github/workflows/fedora_35.yml
  .github/workflows/opensuse_15_1.yml
  .github/workflows/opensuse_15_2.yml
  .github/workflows/ubuntu_16_04.yml
  .github/workflows/ubuntu_18_04.yml
  .github/workflows/ubuntu_20_04.yml
  .github/workflows/ubuntu_21_04.yml
  .github/workflows/ubuntu_21_10.yml
  .gitlab.mk
  debian/rules
  rpm/tarantool.spec
Labels: full-ci

#7120 test: fix luatest server cleanup
  test/luatest_helpers/server.lua
Labels: full-ci

#7118 cleanup: delete old unused files
  .appveyor.yml
  .gitignore
  Jenkinsfile
  snapcraft.yaml
Labels: full-ci

#7079 datetime: handle timezone names in tz
  changelogs/unreleased/gh-7076-tz-attributes.md
  extra/exports
  src/lib/core/datetime.c
  src/lib/core/datetime.h
  src/lib/tzcode/strftime.c
  src/lua/datetime.lua
  src/lua/tnt_datetime.c
  test/app-tap/datetime.test.lua
Labels: teamL, full-ci

#6821 datetime: make date.new{} and date:set{} equivalent
  changelogs/unreleased/gh-6793-datetime-set-with-tzoffset.md
  src/lua/datetime.lua
  test/app-tap/datetime.test.lua
Labels: 1sp, teamL, full-ci

#7134 ci: add Ubuntu Jammy (22.04) workflow
  .github/workflows/ubuntu_22_04.yml
  .github/workflows/ubuntu_22_04_aarch64.yml
Labels: full-ci

#7135 ci: add Ubuntu Hirsute/Impish aarch64 workflows
  .github/workflows/ubuntu_21_04_aarch64.yml
  .github/workflows/ubuntu_21_10_aarch64.yml
Labels: full-ci

#7139 ci: add Ubuntu Groovy (20.10) workflow
  .github/workflows/ubuntu_20_10.yml
  .github/workflows/ubuntu_20_10_aarch64.yml
Labels: full-ci

#7136 iproto: log error before iproto_write_error
  src/box/iproto.cc
  test/box-luatest/gh_6890_iproto_error_use_after_free_test.lua
Labels: full-ci

#7077 mvcc: fix reverse tree iterators gap tracking
  changelogs/unreleased/gh-7113-rev-tree-iters-gap-tracking.md
  src/box/memtx_tree.cc
  test/box-luatest/gh_7113_rev_tree_iters_gap_tracking_test.lua
Labels: bug, memtx, teamC, mvcc, full-ci

#7140 sql: introduce operator []
  changelogs/unreleased/gh-6251-operator-brackets.md
  extra/addopcodes.sh
  src/box/sql/expr.c
  src/box/sql/mem.c
  src/box/sql/mem.h
  src/box/sql/parse.y
  src/box/sql/vdbe.c
  test/sql-luatest/containers_test.lua
Labels: full-ci

#7095 sql: fix insertion crash
  changelogs/unreleased/gh-7132-sql-insertion-crash.md
  src/box/sql/insert.c
  test/sql-luatest/gh_7132_insertion_crash_test.lua
Labels: full-ci

#7168 ffi: export forgotten fiber_join_timeout symbol
  changelogs/unreleased/gh-7125-export-fiber_join_timeout.md
  extra/exports
  test/app-luatest/gh_7125-export-fiber_join_timeout_test.lua
Labels: full-ci

#7211 fiber: don't skip fiber_obj:info() arguments
  changelogs/unreleased/gh-7210-backtrace-for-fiber_obj-info.md
  src/lua/fiber.c
  test/app-luatest/gh_7210_backtrace_for_fiber_obj_info_test.lua
Labels: full-ci

#7205 applier: add timeout to greeting read
  changelogs/unreleased/gh-7204-replication-greeting-timeout.md
  src/box/applier.cc
  test/replication-luatest/gh_7204_greeting_timeout_test.lua
Labels: full-ci
