Repository tarantool/tarantool, pull requests merged in 2023-01, with the labels that each got.

#8114 xrow: fix crash in xrow_decode_error if msg contains printf specifiers
  changelogs/unreleased/gh-8043-net-box-error.md
  src/box/xrow.c
  test/box-luatest/gh_8043_net_box_error_test.lua
Labels: full-ci

#8112 ci: change macos runners labels
  .github/workflows/osx_11.yml
  .github/workflows/osx_11_aarch64.yml
  .github/workflows/osx_11_aarch64_debug.yml
  .github/workflows/osx_11_lto.yml
  .github/workflows/osx_12.yml
  .github/workflows/osx_12_static_cmake.yml
Labels: full-ci

#8109 lua: speedup uri.unescape()
  src/lib/uri/uri.c
Labels: full-ci, 2.11

#8111 build: fix build fail on clang 15
  changelogs/unreleased/clang-15.md
  cmake/thread.cmake
  extra/lemon.c
  src/box/sql/vdbeaux.c
Labels: full-ci

#8145 ci: change runner dispatch for LuaJIT testing
  .github/workflows/luajit-integration.yml
Labels: full-ci

#8126 coro: fix dereferencing of `void *` pointer warning
  third_party/coro/coro.c
Labels: full-ci

#8166 core: silence libunwind errors
  src/lib/core/backtrace.c
Labels: full-ci

#8019 libunwind: improve incremental build/rebuild
  CMakeLists.txt
  cmake/BuildLibUnwind.cmake
  cmake/ext_project_autotools.cmake
  cmake/utils.cmake
Labels: full-ci

#8165 log: fix inability to start from the root directory
  src/lua/init.lua
  test/app-luatest/gh_8158_start_from_root_dir_test.lua
  test/app-luatest/per_module_log_unit_test.lua
Labels: full-ci

#8159 box: rename cluster to replicaset where visible
  src/box/iproto_constants.c
  src/box/iproto_constants.h
  src/box/lua/iproto.c
  src/box/xrow.c
  test/box-luatest/gh_7894_export_iproto_constants_and_features_test.lua
Labels: full-ci

#8184 test: update compat options tests with server:exec
  test/app-luatest/gh_3012_yaml_prettier_multiline_output_test.lua
  test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua
  test/app-luatest/gh_7746_fiber_channel_close_test.lua
Labels: full-ci

#8193 replication: refuse to connect to master with nil UUID
  src/box/applier.cc
  src/box/errcode.h
  test/box/error.result
  test/replication-luatest/gh_8185_dont_connect_to_nil_uuid_test.lua
Labels: full-ci

#8188 ci: use new approach for returning step output
  .github/workflows/reusable_build.yml
Labels: integration-ci

#8205 box: move flightrec configuration out of CE repository
  src/box/box.cc
  src/box/box.h
  src/box/flightrec.h
  src/box/lua/cfg.cc
  src/main.cc
Labels: full-ci

#8171 raft: fix an assertion failure in raft_stop_candidate
  changelogs/unreleased/gh-8169-raft-assert-on-wal-write.md
  src/lib/raft/raft.c
  test/unit/raft.c
Labels: full-ci

#8176 raft: fix 'manual' nodes bumping the term excessively
  changelogs/unreleased/gh-8168-double-term-bump-on-promote.md
  src/lib/raft/raft.c
  test/replication-luatest/gh_8168_extra_term_bump_test.lua
  test/unit/raft.c
Labels: full-ci

#8178 sql: drop unused modules
  src/box/CMakeLists.txt
  src/box/sql/analyze.c
  src/box/sql/date.c
  src/box/sql/fk_constraint.c
  src/box/sql/legacy.c
  src/box/sql/vdbemem.c
Labels: full-ci

#8210 fiber: return always-zero `cpu_misses` entry to `fiber.top()`
  changelogs/unreleased/gh-5869-remove-fiber-top-cpu_misses.md
  src/lua/fiber.c
  test/app/fiber.result
  test/app/fiber.test.lua
Labels: full-ci

#8119 test: verify net.box on a schema of version 2.1.3
  test/box-luatest/gh_4691_data/00000000000000000004.snap
  test/box-luatest/gh_4691_data/fill.lua
  test/box-luatest/gh_4691_net_box_connect_schema_2_1_3_test.lua
Labels: full-ci

#8179 test: fix for gh_6036 test to avoid flakiness
  test/replication-luatest/gh_6036_qsync_order_test.lua
Labels: full-ci

#8218 test: partially disable election_pre_vote test
  test/replication-luatest/election_pre_vote_test.lua
Labels: full-ci

#8213 Revert "box: forbid DDL operations until box.schema.upgrade"
  changelogs/unreleased/gh-7149-forbid-ddl-until-box-schema-upgrade.md
  src/box/errcode.h
  src/box/lua/load_cfg.lua
  src/box/lua/schema.lua
  src/box/lua/upgrade.lua
  test/box-luatest/gh_7149_forbid_ddl_until_box_schema_upgrade_test.lua
  test/box-luatest/upgrade/1.10/00000000000000000004.snap
  test/box/error.result
Labels: full-ci

#8206 box: make ffi select work on M1
  extra/exports
  src/box/box.cc
  src/box/lua/schema.lua
  static-build/test/exports.test.lua
Labels: full-ci

#8183 applier: fix isolation level of applied transactions
  changelogs/unreleased/gh-8121-memtx-mvcc-replication-stream.md
  src/box/applier.cc
  test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua
Labels: full-ci

#8232 ci: fix alpine workflows for fork pull requests
  .github/workflows/alpine_3_16.yml
  .github/workflows/alpine_3_16_aarch64.yml
Labels: full-ci

#8200 test: add test for #7394 (`space:count` bug in memtx MVCC)
  test/box-luatest/gh_7394_memtx_mvcc_space_cnt_bug_test.lua
Labels: full-ci
