Repository tarantool/tarantool, pull requests merged in 2023-07, with the labels that each got.

#8820 memtx: fix heap-use-after-free of tuple stories caused by space alter
  changelogs/unreleased/gh-8781-heap-use-after-free-in-memtx-tx-delete-gap.md
  src/box/memtx_tx.c
Labels: full-ci

#8833 config: rework the way the meta is populated
  src/box/lua/config/init.lua
  src/box/lua/config/source/env.lua
  src/box/lua/config/source/file.lua
Labels: full-ci

#8835 memtx: fix heap-use-after-free of tuple stories caused by space alter
  changelogs/unreleased/gh-8781-heap-use-after-free-in-memtx-tx-delete-gap.md
  src/box/memtx_tx.c
Labels: full-ci

#8836 [master] test: fix flakiness in gh_6128_background_mode_test (again)
  test/app-luatest/gh_6128_background_mode_test.lua
Labels: full-ci

#8840 ci/cd: drop distro-specific packaging workflows
  .github/workflows/alpine_3_16.yml
  .github/workflows/alpine_3_16_aarch64.yml
  .github/workflows/centos_7.yml
  .github/workflows/centos_7_aarch64.yml
  .github/workflows/centos_8.yml
  .github/workflows/centos_8_aarch64.yml
  .github/workflows/debian_10.yml
  .github/workflows/debian_10_aarch64.yml
  .github/workflows/debian_11.yml
  .github/workflows/debian_11_aarch64.yml
  .github/workflows/debian_9.yml
  .github/workflows/fedora_34.yml
  .github/workflows/fedora_34_aarch64.yml
  .github/workflows/fedora_35.yml
  .github/workflows/fedora_35_aarch64.yml
  .github/workflows/fedora_36.yml
  .github/workflows/fedora_36_aarch64.yml
  .github/workflows/redos_7_3.yaml
  .github/workflows/ubuntu_16_04.yml
  .github/workflows/ubuntu_18_04.yml
  .github/workflows/ubuntu_20_04.yml
  .github/workflows/ubuntu_20_04_aarch64.yml
  .github/workflows/ubuntu_22_04.yml
  .github/workflows/ubuntu_22_04_aarch64.yml
  changelogs/unreleased/drop-distro-specific-packages.md
  changelogs/unreleased/gc64-packages-only.md
Labels: full-ci

#8580 sql: use xregion_*() functions
  src/box/bind.c
  src/box/lua/execute.c
  src/box/sql.c
  src/box/sql.h
  src/box/sql/build.c
  src/box/sql/func.c
  src/box/sql/mem.c
  src/box/sql/select.c
  src/box/sql/sqlInt.h
  src/box/sql/tokenize.c
  src/box/sql/update.c
  src/box/sql/util.c
  src/box/sql/vdbe.c
  src/box/sql/where.c
  src/box/sql/whereexpr.c
  src/lib/core/errinj.h
  test/box/errinj.result
Labels: full-ci

#8821 box: fix set language shared between clients via console.connect
  changelogs/unreleased/gh-8817-bug-fix-set-language-shared-between-conn-clients.md
  src/box/lua/console.lua
  test/box-luatest/gh_8817_bug_set_language_shared_test.lua
Labels: full-ci

#8841 Fix teardown in gh_6128_background_mode_test.lua
  test/app-luatest/gh_6128_background_mode_test.lua
Labels: full-ci

#8857 Revert "box: fix shared lang between connected clients" from release/2.10
  changelogs/unreleased/gh-8817-bug-fix-set-language-shared-between-conn-clients.md
  src/box/lua/console.lua
  test/box-luatest/gh_8817_bug_set_language_shared_test.lua
Labels: full-ci

#8863 test: run tests in config test suite in parallel
  test/config-luatest/suite.ini
Labels: full-ci

#8856 config: fix error message during reload
  changelogs/unreleased/gh-8861-cluster-config-error-message.md
  src/box/lua/config/init.lua
  test/config-luatest/reload_test.lua
Labels: full-ci

#8860 config: introduce remaining vinyl options
  changelogs/unreleased/gh-8861-vinyl-options.md
  src/box/lua/config/instance_config.lua
  test/config-luatest/cluster_config_schema_test.lua
  test/config-luatest/config_test.lua
  test/config-luatest/instance_config_schema_test.lua
Labels: full-ci

#8858 compat: add is_new and is_old to options
  changelogs/unreleased/gh-8807-compat-is-new-old.md
  src/lua/compat.lua
  test/app-luatest/gh_7000_compat_module_test.lua
Labels: full-ci

#8797 exports: clean up LuaJIT public interfaces
  changelogs/unreleased/gh-3680-export-all-luajit-public-symbols.md
  extra/exports
  test/app-luatest/gh_3680_export_all_luajit_symbols_test.lua
Labels: full-ci, integration-ci

#8874 compat: fix err msg in compat.<option>:is_new()
  src/lua/compat.lua
  test/app-luatest/gh_7000_compat_module_test.lua
Labels: full-ci

#8870 cmake: introduce FIBER_STACK_SIZE option
  CMakeLists.txt
  changelogs/unreleased/add-fiber-stack-size-option-to-cmake.md
  cmake/SetFiberStackSize.cmake
  src/lib/core/fiber.c
  test/unit/fiber_stack.c
Labels: full-ci

#8873 vinyl: fix use-after-free in `vy_read_iterator_next`
  changelogs/unreleased/gh-8852-vy-read-iterator-use-after-free-fix.md
  src/box/vy_history.c
  src/box/vy_history.h
  src/box/vy_read_iterator.c
Labels: full-ci

#8879 Allow to truncate temporary and local spaces in the read-only mode
  changelogs/unreleased/gh-5616-temp-space-truncate-ro.md
  src/box/alter.cc
  src/box/box.cc
  src/box/box.h
  test/box-luatest/gh_5616_temp_space_truncate_ro_test.lua
  test/replication/anon.result
  test/replication/anon.test.lua
Labels: full-ci

#8891 test: reset readline configuration for justrun too
  test/justrun.lua
Labels: full-ci

#8882 datetime: allow boundary values for interval.new
  changelogs/unreleased/gh-8878-interval-boundaries-fix.md
  src/lua/datetime.lua
  test/app-tap/datetime.test.lua
Labels: full-ci

#8896 lua: replace `api_check()` with `assert()`
  src/lua/utils.c
Labels: lua, luajit misuse, code health, full-ci

#8895 config: introduce feedback options
  changelogs/unreleased/gh-8861-feedback-options.md
  src/box/lua/config/instance_config.lua
  test/config-luatest/cluster_config_schema_test.lua
  test/config-luatest/config_test.lua
  test/config-luatest/instance_config_schema_test.lua
Labels: full-ci

#8898 config: introduce memtx.sort_threads option
  changelogs/unreleased/gh-8861-memtx.sort_threads-option.md
  src/box/lua/config/instance_config.lua
  test/config-luatest/cluster_config_schema_test.lua
  test/config-luatest/config_test.lua
  test/config-luatest/instance_config_schema_test.lua
Labels: full-ci

#8888 msgpack: fix decoding intervals with int64
  changelogs/unreleased/gh-8887-fix-interval-int64.md
  src/lib/core/mp_interval.c
  test/app-tap/datetime.test.lua
  test/unit/interval.c
Labels: full-ci

#8831 sql: fix wrong region allocation
  src/box/sql/select.c
Labels: full-ci

#8903 config: introduce bootstrap_leader option
  changelogs/unreleased/gh-8861-bootstrap_leader-option.md
  src/box/lua/config/applier/box_cfg.lua
  src/box/lua/config/cluster_config.lua
  src/box/lua/config/configdata.lua
  test/config-luatest/config_test.lua
  test/config-luatest/instance_config_schema_test.lua
Labels: full-ci

#8897 config: introduce flightrec options
  changelogs/unreleased/gh-8861-flightrec-options.md
  src/box/lua/config/instance_config.lua
  test/config-luatest/cluster_config_schema_test.lua
  test/config-luatest/config_test.lua
  test/config-luatest/instance_config_schema_test.lua
Labels: full-ci

#8908 [2.11] sql: fix wrong region allocation
  src/box/sql/select.c
Labels: full-ci

#8788 relay: fix unterminated final_join thread
  src/box/box.cc
  src/box/relay.cc
  src/box/relay.h
  test/replication/anon_register_gap.result
  test/replication/anon_register_gap.test.lua
Labels: full-ci

#8864 test: fix flakiness in gh_5568_read_only_reason
  test/replication-luatest/gh_5568_read_only_reason_test.lua
Labels: full-ci

#8916 applier: fix use after free
  src/box/applier.cc
Labels: full-ci

#8883 config: add security section to schema
  changelogs/unreleased/gh-8861-security-options.md
  src/box/lua/config/instance_config.lua
  test/config-luatest/cluster_config_schema_test.lua
  test/config-luatest/config_test.lua
  test/config-luatest/instance_config_schema_test.lua
Labels: full-ci

#8920 test: enable JIT back in app-luatest/http_client_test
  test/app-luatest/http_client_test.lua
Labels: full-ci

#8918 config: fix 'instance not found' failure message
  src/box/lua/config/init.lua
Labels: full-ci

#8924 change BACKUP_STORAGE URL for static build
  static-build/cmake/AddDependencyProjects.cmake
Labels: full-ci
