Repository tarantool/tarantool, pull requests merged in 2023-02, with the labels that each got.

#8221 raft: fix box.ctl.promote() hanging when cannot gather a quorum
  src/box/raft.c
  src/lib/raft/raft.c
  test/replication-luatest/election_pre_vote_test.lua
  test/replication-luatest/gh_8168_extra_term_bump_test.lua
  test/unit/raft.c
Labels: full-ci

#8243 box: fix function definition wrong options error message
  changelogs/unreleased/gh-7972-func-def-wrong-options-err-msg.md
  src/box/alter.cc
  src/box/errcode.h
  test/box-luatest/gh_7972_func_def_err_conditions_test.lua
  test/box/error.result
Labels: full-ci

#8254 test: use unix sockets for iproto in box-py tests
  test/box-py/iproto.test.py
  test/box-py/suite.ini
Labels: full-ci

#8253 lua: drop luaL_register_module()
  src/lua/utils.c
  src/lua/utils.h
Labels: code health, full-ci

#8247 sql: add missing malloc failure handling
  changelogs/unreleased/ghs-65-68-malloc-failure.md
  src/box/sql/select.c
  src/box/sql/trigger.c
Labels: full-ci

#8258 datetime: fix precision overlflow
  changelogs/unreleased/fix-datetime-width-overflow.md
  src/lib/tzcode/strftime.c
  test/app-tap/datetime.test.lua
Labels: full-ci

#8262 bitset: fix index size calculation
  changelogs/unreleased/gh-5809-bitset-index-len-crash.md
  src/lib/bitset/index.h
  test/box-luatest/gh_5809_bitset_index_len_crash_test.lua
  test/unit/bitset_index.c
Labels: full-ci

#8264 [1.10] test: fix autorequire luatest module
  test/app-luatest/digest_crc32_recording_test.lua
  test/app-luatest/gh_4963_fio_pread_err_msg_test.lua
  test/app-luatest/gh_5747_crash_multiple_args_test.lua
  test/app-luatest/http_client_test.lua
  test/app-luatest/msgpack_test.lua
  test/box-luatest/gh_6647_yield_gc_hook_test.lua
  test/box-luatest/gh_6794_recover_nonmatching_xlogs_test.lua
  test/box-luatest/gh_7014_session_disconnect_peer_test.lua
  test/replication-luatest/gh_6966_readonly_bootstrap_test.lua
  test/replication-luatest/quorum_misc_test.lua
  test/vinyl-luatest/gh_6778_recovery_crash_test.lua
  test/vinyl-luatest/gh_7947_tuple_missing_after_rollback_delete_test.lua
  test/vinyl-luatest/update_optimize_test.lua
Labels: full-ci

#8282 log: print build target triplet alongside with the version
  changelogs/unreleased/log-build-target-triplet.md
  src/main.cc
Labels: full-ci

#8292 static-build: move all patches to patches sub-directory
  .gitignore
  static-build/cmake/AddDependencyProjects.cmake
  static-build/patches/openssl-111q-gh-18720.patch
  static-build/patches/readline80-001.patch
Labels: full-ci

#8293 ci: run static-build workflows on 'static-build-ci' label
  .github/workflows/osx_12_static_cmake.yml
  .github/workflows/static_build.yml
  .github/workflows/static_build_cmake_linux.yml
Labels: static-build-ci

#8281 memtx: fix potential NULL dereference in memtx_space_ephemeral_delete
  src/box/memtx_space.c
Labels: full-ci

#8286 static-build: fix potential NULL deref in openssl
  static-build/cmake/AddDependencyProjects.cmake
  static-build/patches/openssl-tarantool-security-54.patch
Labels: static-build-ci

#8297 [2.10] ci: add more testing for macOS 12 and 13
  .github/workflows/osx_11_lto.yml
  .github/workflows/osx_12.yml
  .github/workflows/osx_debug.yml
  .github/workflows/osx_release.yml
  .github/workflows/osx_release_lto.yml
  .github/workflows/osx_static_cmake.yml
  .test.mk
Labels: full-ci

#8298 [1.10] ci: add more testing for macOS 12 and 13
  .github/workflows/osx_debug.yml
  .github/workflows/osx_release.yml
  .github/workflows/osx_release_lto.yml
  .test.mk
Labels: full-ci

#8302 static-build: don't use cat to apply multiple patches
  static-build/cmake/AddDependencyProjects.cmake
Labels: static-build-ci

#8304 box: replace malloc with xmalloc in key_def_dup
  src/box/index_def.c
  src/box/key_def.c
  src/box/key_def.h
  src/box/merger.c
  src/box/vy_lsm.c
  src/box/vy_scheduler.c
Labels: full-ci

#8276 core: check event loop creation in fiber_init()
  src/lib/core/fiber.c
  src/main.cc
Labels: full-ci

#8291 static-build: fix potential NULL dereference in openssl
  static-build/cmake/AddDependencyProjects.cmake
  static-build/patches/openssl-tarantool-security-27.patch
Labels: static-build-ci

#8305 sql: properly check result of sql_get_coll_seq()
  src/box/sql/expr.c
  test/sql-luatest/collation_test.lua
  test/sql/collation.result
  test/sql/collation.test.lua
Labels: full-ci

#8307 box: don't check return values of some cfg_gets() for NULL
  src/box/box.cc
Labels: full-ci

#8135 box: support downgrading of system spaces
  changelogs/unreleased/downgrade.md
  src/box/lua/upgrade.lua
  test/box-luatest/downgrade_helper.lua
  test/box-luatest/downgrade_test.lua
Labels: full-ci

#8195 box: remove dont_check option
  src/box/lua/load_cfg.lua
  src/box/lua/schema.lua
Labels: full-ci

#8306 box: check tuple_field_by_path first argument type
  src/box/lua/tuple.c
Labels: full-ci

#8244 Fixes syslog facility
  changelogs/unreleased/gh-8269-log-syslog-incorrect-facility.md
  src/lib/core/say.c
Labels: full-ci

#8231 feedback: send default metrics
  changelogs/unreleased/gh_8192_feedback_metrics.md
  src/box/lua/feedback_daemon.lua
  src/box/lua/load_cfg.lua
  test/box-luatest/gh_8192_feedback_daemon_metrics_test.lua
  test/box/admin.result
  test/box/cfg.result
Labels: full-ci

#8329 upgrade: enable system triggers back on errors
  src/box/lua/upgrade.lua
Labels: full-ci

#8337 static-build: fix possible div-by-zero in openssl
  static-build/cmake/AddDependencyProjects.cmake
  static-build/patches/openssl-tarantool-security-90.patch
Labels: static-build-ci

#8339 static-build: fix readline read of uninit variable
  static-build/cmake/AddDependencyProjects.cmake
  static-build/patches/readline-tarantool-security-95.patch
Labels: static-build-ci

#8343 box: handle `region_alloc` failure in `tuple_field_map_create_plain`
  src/box/tuple_format.c
Labels: full-ci

#8345 memtx: add one more test for functional index
  test/box-luatest/gh-6786_func_index_iterator_stable_test.lua
Labels: full-ci

#8334 [alternative implementation] luajit: proxy -j and -b flags
  changelogs/unreleased/gh-5541-proxy-luajit-flags.md
  src/CMakeLists.txt
  src/lua/dobytecode.lua
  src/lua/dojitcmd.lua
  src/lua/init.c
  src/lua/init.h
  src/main.cc
  test/box-py/args.result
  test/box-py/args.test.py
Labels: full-ci

#8351 lua: panic on suspicious built-in modules manipulations
  src/lua/utils.c
  src/lua/utils.h
  test/app-luatest/override_panic_test.lua
  test/justrun.lua
  test/treegen.lua
Labels: full-ci

#8229 lua/utils: use `index2adr()` instead of index arithmetic
  changelogs/unreleased/gh-8249-lual_checkcdata-with-upvalues.md
  src/lua/serializer.c
  src/lua/utils.c
  src/lua/utils.h
  test/app-tap/module_api.c
  test/app-tap/module_api.test.lua
Labels: full-ci

#8047 httpc: introduce stream input/output interface
  changelogs/unreleased/gh-7845-httpc-stream-io-interface.md
  src/curl.c
  src/curl.h
  src/httpc.c
  src/httpc.h
  src/lua/httpc.c
  src/lua/httpc.lua
  test/app-luatest/http_client_test.lua
Labels: full-ci

#8330 log: allow "tarantool" as module name in `box.cfg{log_modules = {...}}`
  src/lib/core/say.c
  src/lua/log.lua
  test/box-luatest/gh_3211_per_module_log_level_test.lua
Labels: full-ci

#7929 debugger: `tarantool -d` option, step.4
  changelogs/unreleased/gh-7456-console-debugger-option.md
  src/lua/init.c
  src/lua/init.h
  src/main.cc
  test/app-luatest/console_debugger_session_test.lua
  test/app-luatest/debug-self-target.lua
  test/app-luatest/debug-target.lua
  test/box-py/args.result
  third_party/lua/README-luadebug.md
  third_party/lua/luadebug.lua
Labels: full-ci

#8331 box: support downgrading of tuple constraints
  src/box/lua/upgrade.lua
  test/box-luatest/downgrade_test.lua
Labels: full-ci

#8364 test: fix result-file for box-py/args.test.py
  test/box-py/args.result
Labels: full-ci

#8358 net_box: don't use integer implementation defined
  src/box/lua/net_box.c
Labels: full-ci

#8376 vinyl: fix use after free on key alloc error in iterator constructor
  src/box/vinyl.c
  test/vinyl-luatest/gh_8372_key_alloc_error_in_iter_ctor_test.lua
Labels: full-ci
