Repository tarantool/tarantool, pull requests merged in 2023-10, with the labels that each got.

#9214 sql: fix memory leak in SQL parser for column default
  changelogs/unreleased/gh-9159-fix-memleak-in-sql-column-default-parser.md
  src/box/sql/parse.y
Labels: full-ci

#9239 ci: add crud integration test run
  .github/workflows/integration.yml
Labels: integration-ci

#9230 sql: assign collation to indexes in CREATE TABLE
  changelogs/unreleased/gh-9229-no-collation-for-indexes.md
  src/box/sql/build.c
  test/sql-luatest/collation_test.lua
Labels: full-ci

#9246 unit: fix undefined behaviour in prbuf test
  test/unit/prbuf.c
Labels: full-ci

#9070 main: display a message when local console is exited
  changelogs/unreleased/gh-7017-display-message-on-console-exit.md
  src/box/lua/console.c
  src/box/lua/console.h
  src/box/lua/console.lua
  src/main.cc
  test/app-luatest/gh_7017_message_on_console_exit_test.lua
Labels: full-ci

#9251 box: fix `space:bsize()` handling on space alter
  changelogs/unreleased/gh-9247-fix-space-bsize-handling-on-space-alter.md
  src/box/alter.cc
  src/box/blackhole.c
  src/box/memtx_space.c
  src/box/session_settings.c
  src/box/space.c
  src/box/space.h
  src/box/sysview.c
  src/box/vinyl.c
  test/box-luatest/gh_9247_bsize_on_concurrent_dml_and_alter_test.lua
Labels: full-ci

#9231 config: add lua_eval, lua_call and sql support to creds
  changelogs/unreleased/gh-8967-add-lua_eval-lua_call-sql.md
  src/box/lua/config/applier/credentials.lua
  src/box/lua/config/instance_config.lua
  test/config-luatest/credentials_applier_test.lua
  test/config-luatest/instance_config_schema_test.lua
Labels: full-ci

#9250 config: update password hashes after auth_type change
  changelogs/unreleased/gh-8967-creds-consider-auth-type.md
  src/box/lua/config/applier/credentials.lua
  test/config-luatest/credentials_applier_test.lua
Labels: full-ci

#9267 console: forward original URI to net.box when connecting over IPROTO
  src/box/lua/console.lua
Labels: full-ci

#9264 app: start init script event loop explicitly
  changelogs/unreleased/gh-9266-fix-on-shutdown-and-osexit-from-cmd-expr.md
  src/lua/init.c
  test/box-luatest/gh_9266_fix_on_shutdown_and_osexit_from_cmd_expr_test.lua
Labels: full-ci

#9273 box: call `tuple_free` from `box_free`
  perf/memtx.cc
  src/box/box.cc
  src/box/field_default_func.c
  src/box/field_default_func.h
  src/box/memtx_engine.cc
  src/box/tuple_format.c
  test/unit/tuple_format.c
Labels: full-ci

#9279 util: introduce the ALWAYS_INLINE macro
  src/box/tuple_compare.cc
  src/trivia/util.h
Labels: full-ci

#9257 ci: dockerize linux workflows
  .github/workflows/codeql.yml
  .github/workflows/coverage.yml
  .github/workflows/debug.yml
  .github/workflows/debug_aarch64.yml
  .github/workflows/lint.yml
  .github/workflows/memtx_allocator_based_on_malloc.yml
  .github/workflows/out_of_source.yml
  .github/workflows/release.yml
  .github/workflows/release_lto.yml
  .github/workflows/source.yml
  .github/workflows/static_build.yml
  .github/workflows/static_build_cmake_linux.yml
  .github/workflows/submodule_update.yml
Labels: full-ci

#9280 fiber: use alternative signal stack
  changelogs/unreleased/gh-9222-sigaltstack.md
  src/lib/core/crash.c
  src/lib/core/fiber.c
  test/unit/guard.cc
Labels: asan-ci

#9269 replication: improve name conflict error message
  src/box/errcode.h
  test/replication-luatest/cluster_name_test.lua
  test/replication-luatest/instance_name_test.lua
  test/replication-luatest/replicaset_name_test.lua
Labels: full-ci

#9284 test: increase expected selectG execution time for debug ASAN build
  test/sql-tap/selectG.test.lua
Labels: asan-ci

#9290 log: make `log.cfg{modules=...}` work as `box.cfg{log_modules=...}`
  changelogs/unreleased/gh-7962-log-cfg-modules-fix.md
  src/box/lua/load_cfg.lua
  src/lua/log.lua
  test/box-luatest/gh_3211_per_module_log_level_test.lua
Labels: full-ci

#9293 box: disallow granting execute privilege on space
  changelogs/unreleased/gh-9277-space-execute-priv.md
  src/box/lua/load_cfg.lua
  src/box/lua/schema.lua
  test/box-luatest/gh_9277_space_execute_priv_test.lua
  test/box-py/iproto.result
  test/box-py/iproto.test.py
  test/box/access.result
  test/box/access.test.lua
  test/box/access_misc.result
  test/box/access_misc.test.lua
  test/box/access_sysview.result
  test/box/access_sysview.test.lua
  test/box/net.box_field_names_gh-2978.result
  test/box/net.box_field_names_gh-2978.test.lua
  test/box/net.box_get_connection_object.result
  test/box/net.box_get_connection_object.test.lua
  test/sql/triggers.result
  test/sql/triggers.test.lua
Labels: full-ci

#9305 test: add WA for #3807 to wal_off/oom.test
  test/wal_off/oom.result
  test/wal_off/oom.test.lua
Labels: full-ci

#9238 fiber: basic api exports
  changelogs/unreleased/fiber-basic-api.md
  extra/exports
  src/lib/core/fiber.c
  src/lib/core/fiber.h
  test/app-tap/module_api.c
  test/app-tap/module_api.test.lua
Labels: full-ci

#9316 config: fix hanging alert about missing name
  src/box/lua/config/applier/box_cfg.lua
Labels: full-ci

#9317 lua: add helpers for encoding/decoding IPROTO packets
  changelogs/unreleased/gh-8054-lua-iproto-encoder.md
  src/box/iproto.cc
  src/box/iproto_constants.h
  src/box/lua/iproto.c
  test/app-luatest/iproto_encoder_test.lua
  test/box-luatest/ghs_16_user_enumeration_test.lua
Labels: full-ci
