Repository tarantool/tarantool, pull requests merged in 2023-03, with the labels that each got.

#8377 box: make `space_foreach()` strictly ordered
  changelogs/unreleased/gh-7954-sort-spaces-in-snapshot-by-id.md
  src/box/space.c
  src/box/space.h
  src/box/space_cache.c
  src/box/space_cache.h
  test/box-luatest/gh_7954_sort_spaces_in_snap_by_id_test.lua
Labels: full-ci

#8390 test: fix gh_7974_force_recovery_bugs flaky test
  test/box-luatest/gh_7974_force_recovery_bugs_test.lua
Labels: full-ci

#8380 replication: add remote peer connection timeout
  changelogs/unreleased/gh-7294-long-reconnection-fix.md
  src/box/applier.cc
  test/replication-luatest/gh_7294_dont_connect_infinitely_test.lua
Labels: full-ci

#8385 main: fix wrong log level printed during first `box.cfg{}`
  src/lib/core/say.c
  src/lib/core/say.h
  src/main.cc
  test/app-luatest/gh_8287_wrong_initial_log_level_printed_test.lua
Labels: full-ci

#8275 box: add `check_select_safety` to `box.internal`
  src/box/lua/schema.lua
Labels: full-ci

#8406 test: add rule to ignore Makefile
  .gitignore
Labels: full-ci

#8400 httpc: check region_join result
  src/httpc.c
Labels: full-ci

#8388 msgpack: fix unsafe extension decoding
  changelogs/unreleased/ghs-73-unsafe-extensions-decoding.md
  extra/exports
  src/box/bind.c
  src/box/mp_error.cc
  src/box/mp_error.h
  src/box/msgpack.c
  src/box/sql/mem.c
  src/lib/core/decimal.c
  src/lib/core/mp_interval.c
  src/lib/core/mp_interval.h
  src/lua/msgpack.c
  src/lua/msgpackffi.lua
  src/lua/tnt_datetime.c
  test/box-luatest/gh_6857_tuple_ext_validation_test.lua
  test/unit/mp_error.cc
Labels: full-ci

#8409 test: fix fail of gh_4669_applier_reconnect_test
  test/replication-luatest/gh_4669_applier_reconnect_test.lua
Labels: full-ci

#8435 box: fix 64-bit schema version for message pack.
  src/box/lua/net_box.c
  src/box/xrow.c
  src/box/xrow.h
  test/app/socket.result
  test/box-luatest/iproto_request_handlers_overriding_test.lua
Labels: full-ci

#8416 sql: incomparable types in ORDER BY and GROUP BY
  changelogs/unreleased/gh-6668-ordering-incomparable-types.md
  src/box/sql/resolve.c
  test/sql-luatest/gh_6668_problems_with_map_array_test.lua
  test/sql-luatest/interval_test.lua
  test/sql-tap/uuid.test.lua
Labels: full-ci

#8439 build: drop unused variable detected by clang 15
  src/box/sql/vdbe.c
Labels: full-ci, 3.0

#8455 [2.10] sql: add return value check for sql_key_info_new()
  src/box/sql/select.c
Labels: full-ci

#8453 merger: fix signed integer overflow
  src/box/lua/merger.c
  test/box-tap/merger.test.lua
Labels: full-ci, 2.10

#8454 box: fix wrong validation of region_alloc() result
  src/box/lua/misc.cc
Labels: full-ci

#8447 net.box: fix crash when remote space field has unknown type
  changelogs/unreleased/gh-4632-net-box-unknown-field-type.md
  src/box/lua/misc.cc
  test/box-luatest/gh_4632_net_box_unknown_field_type_test.lua
Labels: full-ci

#8456 sql: fix wrong int to dec conversion
  changelogs/unreleased/gh-8460-wrong-int-to-dec-convertion-in-arithmetic.md
  src/box/sql/mem.c
  test/sql-luatest/gh_8460_wrong_int_to_dec_test.lua
Labels: full-ci

#8462 box: fix big number encoding by msgpackffi
  changelogs/unreleased/gh-6119-fix-number-mp-encode.md
  src/lua/msgpackffi.lua
  test/app-luatest/gh_6119_number_mp_encode_test.lua
  test/engine-luatest/gh_6119_select_big_numbers_test.lua
Labels: full-ci

#8466 box: fix a crash on unknown function option
  changelogs/unreleased/gh-8463-crash-on-create-function
  src/box/func_def.c
  test/box-luatest/func_test.lua
Labels: full-ci

#8459 downgrade: handle function option `takes_raw_args`
  changelogs/unreleased/gh-8457-downgrade-handle-takes-raw-args.md
  src/box/lua/upgrade.lua
  test/box-luatest/downgrade_test.lua
Labels: full-ci

#8471 memtx: refactor statistics reporting
  changelogs/unreleased/gh-8448-box-stat-memtx-func.md
  src/box/lua/stat.c
  src/box/memtx_engine.cc
  src/box/memtx_engine.h
  test/box-luatest/gh_6150_memtx_tx_memory_monitoring_test.lua
Labels: full-ci

#8414 relay: send heartbeats on top of replication stream
  changelogs/unreleased/gh-7515-syncing-follower-notices-leader-hang.md
  src/box/applier.cc
  src/box/relay.cc
  test/replication-luatest/gh_7515_sync_node_sees_leader_hang_test.lua
Labels: full-ci

#8484 build: add tt weak dependency
  changelogs/unreleased/no-gh-add-tt-dependency.md
  debian/control
  rpm/tarantool.spec
Labels: full-ci

#8498 console: fix :endswith() err in tntctl connection
  changelogs/unreleased/gh-8374-local-print-accepts-non-strings.md
  src/box/lua/console.lua
Labels: full-ci

#8510 memtx: introduce read view statistics
  changelogs/unreleased/gh-8501-memtx-read-view-stats.md
  src/box/memtx_engine.cc
  test/box-luatest/gh_8501_memtx_read_view_stats_test.lua
Labels: full-ci

#8519 prbuf: remove dead code
  extra/exports
  src/lib/core/prbuf.c
  src/lib/core/prbuf.h
  src/lua/buffer.lua
  test/app-luatest/prbuf_test.lua
  test/unit/prbuf.c
Labels: full-ci

#8520 test: fix 4317_console_backslash_test to use defaut .inputrc
  test/app-luatest/gh_4317_console_backslash_test.lua
Labels: full-ci

#8470 test: improve test for replace on primary index altering
  test/engine-luatest/gh_4973_concurrent_alter_fails_test.lua
  test/engine/engine.cfg
  test/engine/gh-4973-concurrent-alter-fails.result
  test/engine/gh-4973-concurrent-alter-fails.test.lua
  test/engine/suite.ini
Labels: full-ci
