Repository tarantool/tarantool, pull requests merged in 2024-01, with the labels that each got.

#9583 test: fix flaky tests when JIT is enabled
  test/box/lua/utils.lua
  test/box/net.box_reconnect_after_gh-3164.result
  test/box/net.box_reconnect_after_gh-3164.test.lua
Labels: luajit, flaky test, full-ci

#9589 index: introduce weak reference
  src/box/CMakeLists.txt
  src/box/box.cc
  src/box/index.cc
  src/box/index.h
  src/box/index_weak_ref.c
  src/box/index_weak_ref.h
  src/box/memtx_bitset.cc
  src/box/memtx_engine.h
  src/box/memtx_hash.cc
  src/box/memtx_rtree.cc
  src/box/memtx_tree.cc
  src/box/sql.c
  src/box/sysview.c
  src/box/vinyl.c
Labels: full-ci

#9592 box: introduce fixed-size numeric field types
  changelogs/unreleased/gh-9548-introduce-fixed-size-numeric-types.md
  src/box/errcode.h
  src/box/field_def.c
  src/box/field_def.h
  src/box/tuple_format.c
  src/box/tuple_format.h
  test/box/error.result
  test/engine-luatest/gh_9548_fixed_size_numeric_types_test.lua
  test/unit/tuple_format.c
Labels: full-ci

#9594 space: optimize lookup by id
  src/box/space_cache.c
  src/box/space_cache.h
  test/unit/vy_point_lookup.c
Labels: full-ci

#9600 test: fix gh-2717-no-quit-sigint test
  test/app-tap/gh-2717-no-quit-sigint.test.lua
Labels: full-ci

#9615 box: allow indexing of fixed-size numeric field types
  src/box/index_def.c
  src/box/index_def.h
  src/box/memtx_space.c
  src/box/tuple_compare.cc
  src/box/vinyl.c
  test/engine-luatest/gh_9548_fixed_size_numeric_types_test.lua
Labels: full-ci

#9619 test: fix fix_lua_loader_error_handling on macOS
  test/app-luatest/fix_lua_loader_error_handling_test.lua
Labels: osx, full-ci, test

#9609 config: introduce config.etcd.watchers options
  changelogs/unreleased/ghe-647-config-etcd-watchers-options.md
  src/box/lua/config/instance_config.lua
  test/config-luatest/instance_config_schema_test.lua
Labels: full-ci

#9604 box: finish client fibers on shutdown
  src/box/box.cc
  src/box/lua/console.lua
  src/box/memtx_engine.cc
  src/box/replication.cc
  src/box/vy_quota.c
  src/box/vy_scheduler.c
  src/lib/core/errinj.h
  src/lib/core/fiber.c
  src/lib/core/fiber.h
  src/lib/core/fiber_pool.c
  src/lua/fiber.c
  src/lua/fiber.lua
  src/lua/init.lua
  src/main.cc
  test/box-luatest/gh_7743_term_initial_cfg_snap_test.lua
  test/box-luatest/gh_8530_alter_space_snapshot_test.lua
  test/box/errinj.result
  test/replication-luatest/shutdown_test.lua
  test/replication-py/cluster.test.py
  test/replication/anon.result
  test/replication/anon.test.lua
  test/replication/force_recovery.result
  test/replication/force_recovery.test.lua
  test/replication/gh-3637-misc-error-on-replica-auth-fail.result
  test/replication/gh-3637-misc-error-on-replica-auth-fail.test.lua
  test/replication/gh-4739-vclock-assert.result
  test/replication/gh-4739-vclock-assert.test.lua
  test/replication/gh-5613-bootstrap-prefer-booted.result
  test/replication/gh-5613-bootstrap-prefer-booted.test.lua
  test/replication/gh-5806-xlog-cleanup.result
  test/replication/gh-5806-xlog-cleanup.test.lua
  test/replication/prune.result
  test/replication/prune.test.lua
  test/replication/replica_auth.lua
  test/replication/replica_rejoin.result
  test/replication/replica_rejoin.test.lua
  test/unit/fiber.cc
  test/unit/fiber.result
  test/vinyl/errinj.result
  test/vinyl/errinj.test.lua
  test/vinyl/errinj_vylog.result
  test/vinyl/errinj_vylog.test.lua
  test/xlog/panic_on_wal_error.result
  test/xlog/panic_on_wal_error.test.lua
Labels: full-ci

#9626 perf: add column scan test
  perf/lua/CMakeLists.txt
  perf/lua/column_scan.lua
  perf/lua/column_scan_module.c
Labels: full-ci
