Repository tarantool/tarantool, pull requests merged in 2024-10, with the labels that each got.

#10613 gcov: fix clang build
  cmake/profile.cmake
  src/trivia/util.h
Labels: full-ci

#10638 third_party: fix `nanoarrow` install directory
  cmake/BuildNanoarrow.cmake
Labels: full-ci

#10464 test: fix flaky gh_9918_synchro_queue_additional_info_test.lua
  test/replication-luatest/gh_9918_synchro_queue_additional_info_test.lua
Labels: full-ci

#10642 [backport 3.2] test: fix flaky gh_9918_synchro_queue_additional_info_test.lua
  test/replication-luatest/gh_9918_synchro_queue_additional_info_test.lua
Labels: full-ci

#10637 net_box: fix a crash when a trigger deletes itself
  changelogs/unreleased/gh-10622-net-box-trigger-crash-on-self-delete.md
  src/lua/trigger.c
  test/box-luatest/gh_10622_net_box_trigger_crash_on_self_delete_test.lua
Labels: full-ci

#10654 httpc: replace ibuf_alloc with xibuf_alloc
  src/httpc.c
Labels: full-ci

#10656 [Backport 3.2] httpc: replace ibuf_alloc with xibuf_alloc
  src/httpc.c
Labels: full-ci

#10657 [Backport 2.11] httpc: replace ibuf_alloc with xibuf_alloc
  src/httpc.c
Labels: full-ci

#10644 index_def: make index_def_new non-failing
  src/box/alter.cc
  src/box/index_def.c
  src/box/index_def.h
  src/box/key_def.c
  src/box/schema.cc
  src/box/sql.c
  src/box/sql/build.c
  src/box/sql/where.c
Labels: full-ci

#10661 bps: improve tree view tests
  test/unit/bps_tree_iterator.cc
  test/unit/bps_tree_view.c
Labels: full-ci

#10664 box: log error that caused initial checkpoint failure
  src/box/box.cc
Labels: full-ci

#10618 schema: broadcast persistent schema version in box.status
  changelogs/unreleased/gh-10546-schema-version-broadcast.md
  src/box/alter.cc
  src/box/box.cc
  src/box/box.h
  test/box-luatest/builtin_events_test.lua
  test/box-luatest/upgrade_to_3_0_0_test.lua
Labels: full-ci

#10499 datetime: add additional tests for a strptime()
  test/app-tap/datetime.test.lua
Labels: full-ci

#10554 cmake: turn on sysmalloc with ASAN build
  cmake/luajit.cmake
Labels: build, full-ci, asan-ci

#10667 [Backport 3.2] test: add additional tests for a strptime()
  test/app-tap/datetime.test.lua
Labels: full-ci

#10668 [Backport 2.11] test: add additional tests for a strptime()
  test/app-tap/datetime.test.lua
Labels: full-ci

#10672 build: don't depend on libidn2
  cmake/BuildLibCURL.cmake
Labels: full-ci

#10676 [backport 3.2] build: don't depend on libidn2
  cmake/BuildLibCURL.cmake
Labels: full-ci

#10677 [backport 2.11] build: don't depend on libidn2
  cmake/BuildLibCURL.cmake
Labels: full-ci

#10650 config/schema: improve unexpected array error
  changelogs/unreleased/config-schema-improve-unexpected-array-message.md
  src/box/lua/config/utils/schema.lua
  test/config-luatest/schema_test.lua
Labels: full-ci

#10674 box: fix `SIGSEGV` on unaligned access to a struct with extended alignment
  src/box/applier.cc
  src/box/iproto.cc
  src/box/relay.cc
  src/box/replication.cc
  src/trivia/util.h
Labels: full-ci

#10683 config: refactor to reuse already calculated values in configdata
  src/box/lua/config/configdata.lua
Labels: full-ci

#10687 [backport 3.2] config: refactor to reuse already calculated values in configdata
  src/box/lua/config/configdata.lua
Labels: full-ci

#10632 cmake: fix build with GCC's AddressSanitizer
  cmake/CheckDependencies.cmake
  cmake/profile.cmake
Labels: full-ci

#10684 say: fix NULL pointer dereference in log_syslog_init
  src/lib/core/say.c
Labels: full-ci

#10605 ci: bump clang version to 19
  .github/workflows/debug_asan_clang.yml
  .github/workflows/release_asan_clang.yml
  .github/workflows/release_clang.yml
  .github/workflows/release_lto_clang.yml
  cmake/BuildLibXXhash.cmake
  cmake/BuildZSTD.cmake
Labels: full-ci

#10690 [Backport 3.2] cmake: fix build with GCC's AddressSanitizer
  cmake/CheckDependencies.cmake
  cmake/profile.cmake
Labels: full-ci

#10700 box: fix `SIGSEGV` on unaligned access to `struct applier`
  src/box/applier.cc
Labels: full-ci

#10706 box/lua: change `space:bsize()` return type from `cdata` to `number`
  changelogs/unreleased/gh-9735-fix-space-bsize-return-type.md
  src/box/lua/schema.lua
  test/box/space_bsize.result
  test/box/space_bsize.test.lua
Labels: full-ci

#10723 [backport] box: export box_slab_info via C API
  src/box/box.cc
  src/box/box.h
  src/box/lua/slab.cc
  src/symbols.c
  test/app-luatest/tnt_internal_symbol_test.lua
Labels: full-ci, do not merge

#10711 memtx: clarify tuples against given index in memtx_tx_snapshot_cleaner
  src/box/memtx_hash.cc
  src/box/memtx_tree.cc
  src/box/memtx_tx.c
  src/box/memtx_tx.h
Labels: full-ci

#10705 box/lua: don't crash on `box.internal.tuple_format.new()` misuse
  src/box/lua/tuple_format.c
  test/box-luatest/gh_4693_formats_for_standalone_tuples_test.lua
Labels: full-ci

#10718 config: fix scaling a replicaset down to one node
  changelogs/unreleased/gh-10716-config-scaling-down.md
  src/box/lua/config/applier/box_cfg.lua
  test/config-luatest/downscaling_test.lua
Labels: full-ci

#10744 [backport 3.2] box/lua: don't crash on box.internal.tuple_format.new() misuse
  src/box/lua/tuple_format.c
  test/box-luatest/gh_4693_formats_for_standalone_tuples_test.lua
Labels: full-ci

#10748 [backport 3.2] config: fix scaling a replicaset down to one node
  changelogs/unreleased/gh-10716-config-scaling-down.md
  src/box/lua/config/applier/box_cfg.lua
  test/config-luatest/downscaling_test.lua
Labels: full-ci

#10750 [backport 2.11] memtx: clarify tuples against given index in memtx_tx_snapshot_cleaner
  src/box/memtx_hash.cc
  src/box/memtx_tree.cc
  src/box/memtx_tx.c
  src/box/memtx_tx.h
Labels: full-ci

#10749 [backport 3.2] memtx: clarify tuples against given index in memtx_tx_snapshot_cleaner
  src/box/memtx_hash.cc
  src/box/memtx_tree.cc
  src/box/memtx_tx.c
  src/box/memtx_tx.h
Labels: full-ci

#10745 log: emit file name and line for all log levels
  changelogs/unreleased/gh-9913-emit-filename-for-all-log-levels.md
  src/lib/core/say.c
  test/box-luatest/gh_3211_per_module_log_level_test.lua
  test/box-tap/gh-4785-syslog.test.lua
  test/config-luatest/log_test.lua
Labels: full-ci

#10743 Generate changelog for 3.2.1
  changelogs/3.2.1.md
  changelogs/unreleased/bump-libcurl-to-8.10.1.md
  changelogs/unreleased/gh-10146-mvcc-ddl-crashes-and-isolation-violation.md
  changelogs/unreleased/gh-10148-fix-small-crash-low-alloc-factor.md
  changelogs/unreleased/gh-10199-luajit-fixes.md
  changelogs/unreleased/gh-10235-consequent-ddl-crash.md
  changelogs/unreleased/gh-10262-inconsistency-between-caches-and-data.md
  changelogs/unreleased/gh-10391-forbid-non-integers-datetime-new.md
  changelogs/unreleased/gh-10391-forbid-non-integers-datetime-set.md
  changelogs/unreleased/gh-10391-forbid-non-integers-sql-datetime.md
  changelogs/unreleased/gh-10420-introduce-tz-option-in-parse.md
  changelogs/unreleased/gh-10476-fix-fkey-constraint-check-memleak.md
  changelogs/unreleased/gh-10477-fix-iproto-override-memleak.md
  changelogs/unreleased/gh-10479-fix-xlog-open-memleak.md
  changelogs/unreleased/gh-10480-fix-replica-disconnect-memleak.md
  changelogs/unreleased/gh-10482-fix-coio-connect-memleak.md
  changelogs/unreleased/gh-10484-fix-space-DDL-memleak.md
  changelogs/unreleased/gh-10485-fix-user-DDL-memleak.md
  changelogs/unreleased/gh-10487-fix-iconv-memleak.md
  changelogs/unreleased/gh-10489-fix-vinyl-on-dump-failure-memleak.md
  changelogs/unreleased/gh-10490-fix-replica-deleted-memleak.md
  changelogs/unreleased/gh-10495-fix-swim-crash-on-shutdown.md
  changelogs/unreleased/gh-10512-fix-vinyl-page-load-error-handling.md
  changelogs/unreleased/gh-10524-use-verbose-level-for-logging-vinyl-ranges.md
  changelogs/unreleased/gh-10551-fix-index-crash-on-OOM-on-rollback.md
  changelogs/unreleased/gh-10553-check-fiber-slice-in-vinyl-index-count.md
  changelogs/unreleased/gh-10555-fix-vinyl-compaction-crash-on-read-error.md
  changelogs/unreleased/gh-10558-fix-vinyl-cache-corruption-on-skipping-unconfirmed-tuple.md
  changelogs/unreleased/gh-10603-fix-vinyl-pk-alter-crash.md
  changelogs/unreleased/gh-10622-net-box-trigger-crash-on-self-delete.md
  changelogs/unreleased/gh-10716-config-scaling-down.md
  changelogs/unreleased/gh-8333-fix-ignoring-tzoffset-in-parse.md
  changelogs/unreleased/gh-9735-fix-space-bsize-return-type.md
  changelogs/unreleased/gh-9917-speed-up-transaction-queue-processing.md
  changelogs/unreleased/libcurl-doc-option-fix.md
  changelogs/unreleased/libcurl-options-fix.md
  src/box/lua/upgrade.lua
Labels: full-ci
