Repository tarantool/tarantool, pull requests merged in 2024-05, with the labels that each got.

#9988 bps: fix the OS X build
  src/lib/salad/bps_tree.h
Labels: osx, full-ci

#9980 box: pass source tuple to `default_func` field option of `space:format`
  changelogs/unreleased/gh-9825-space-format-default-func-tuple-arg.md
  src/box/field_default_func.c
  src/box/field_default_func.h
  src/box/sql/func.c
  src/box/tuple_format.c
  src/box/tuple_format.h
  test/engine-luatest/gh_9825_space_format_default_func_tuple_arg_test.lua
Labels: full-ci

#9983 [backport 3.1] relay: fix timeout on large xlog subscribe start
  changelogs/unreleased/gh-9094-timeout-on-too-big-xlog-subscribe.md
  src/box/relay.cc
  src/lib/core/errinj.h
  test/box/errinj.result
  test/replication-luatest/gh_9094_long_wal_subscribe_test.lua
Labels: full-ci

#9984 [backport 2.11] relay: fix timeout on large xlog subscribe start
  changelogs/unreleased/gh-9094-timeout-on-too-big-xlog-subscribe.md
  src/box/relay.cc
  src/lib/core/errinj.h
  test/box/errinj.result
  test/replication-luatest/gh_9094_long_wal_subscribe_test.lua
Labels: full-ci

#10001 console: create per-session variables scope
  changelogs/unreleased/console-session-scope-vars.md
  src/box/lua/config/instance_config.lua
  src/box/lua/console.lua
  test/app-luatest/console_session_scope_vars_test.lua
  test/config-luatest/cluster_config_schema_test.lua
Labels: full-ci

#10012 vinyl: fix use-after-free of LSM tree in scheduler
  changelogs/unreleased/gh-9995-vy-scheduler-crash-fix.md
  src/box/vy_scheduler.c
Labels: full-ci

#10014 console: autorequire frequently used modules
  changelogs/unreleased/console-autorequire.md
  src/box/lua/console.lua
  test/app-luatest/console_autorequire_test.lua
Labels: full-ci

#10016 vinyl: fix bug when tuple not committed to unique nullable index
  changelogs/unreleased/gh-9769-vy-unique-nullable-index-fix.md
  src/box/vy_lsm.c
  test/engine-luatest/gh_9769_tuple_lost_in_unique_nullable_index_test.lua
Labels: full-ci

#10027 vinyl: fix index build crash on invalid UPSERT
  changelogs/unreleased/gh-10026-vy-index-build-crash-on-invalid-upsert-fix.md
  src/box/vinyl.c
  test/engine-luatest/gh_10026_index_build_crash_on_invalid_upsert_test.lua
  test/vinyl/on_replace.result
Labels: full-ci

#10023 vinyl: fix index name in duplicate key error message
  changelogs/unreleased/gh-5975-vy-duplicate-key-error-fix.md
  src/box/space.c
  src/box/space.h
  src/box/vinyl.c
  test/engine-luatest/gh_5975_duplicate_key_error_test.lua
Labels: full-ci

#10015 wal: fix wal_queue_max_size assignment during initial box.cfg
  changelogs/unreleased/gh-10013-wal-queue-max-size.md
  src/box/box.cc
  src/box/lua/load_cfg.lua
  test/replication-luatest/gh_10013_wal_queue_max_size_test.lua
Labels: full-ci

#10028 box: introduce next and previous prefix iterators
  changelogs/unreleased/gh-9994-next-prefix-iterator.md
  src/box/iterator_type.c
  src/box/iterator_type.h
  src/box/memtx_tree.cc
  test/box-luatest/gh_9994_next_prefix_iterator_test.lua
Labels: full-ci

#9907 space_upgrade: fix crashes on upgrading nullability
  src/box/alter.cc
Labels: full-ci

#10048 ci: temporary disable aarch64 packaging job
  .github/workflows/distrib.yml
Labels: full-ci

#10046 net.replicaset: fix a flaky test
  test/box-luatest/gh_9823_net_replicaset_test.lua
Labels: full-ci

#10051 config: expose configuration status from box.info
  changelogs/unreleased/box-info-config.md
  src/box/lua/info.c
  test/box-luatest/box_info_config_test.lua
  test/box/info.result
Labels: full-ci

#10052 config: give better error if a role is not a table
  changelogs/unreleased/config-not-a-table-role-error-message.md
  src/box/lua/config/applier/roles.lua
  test/config-luatest/roles_test.lua
Labels: full-ci

#10017 static-build: bump the OpenSSL library version to 3.2.1
  changelogs/unreleased/gh-7502-bump-openssl.md
  cmake/BuildOpenSSL.cmake
  patches/openssl-111q-gh-18720.patch
  patches/openssl-tarantool-security-27.patch
  patches/openssl-tarantool-security-54.patch
  patches/openssl-tarantool-security-90.patch
Labels: full-ci, integration-ci, static-build-ci

#10054 [backport 3.1] config: give better error if a role is not a table
  changelogs/unreleased/config-not-a-table-role-error-message.md
  src/box/lua/config/applier/roles.lua
  test/config-luatest/roles_test.lua
Labels: full-ci

#10020 [backport 2.11] static-build: bump the OpenSSL library version to 3.2.1
  changelogs/unreleased/gh-7502-bump-openssl.md
  cmake/BuildOpenSSL.cmake
  patches/openssl-111q-gh-18720.patch
  patches/openssl-tarantool-security-27.patch
  patches/openssl-tarantool-security-54.patch
  patches/openssl-tarantool-security-90.patch
Labels: full-ci, integration-ci, static-build-ci

#10038 test: fix flaky downstream lag test
  test/replication-luatest/gh_9748_downstream_lag_test.lua
Labels: full-ci

#10063 [backport 3.1] test: fix flaky downstream lag test
  test/replication-luatest/gh_9748_downstream_lag_test.lua
Labels: full-ci

#10003 box: prevent demoted leader from being a candidate in the next elections
  changelogs/unreleased/gh-9855-box-ctl-demote-guarantee-demoting.md
  src/box/box.cc
  src/box/raft.c
  src/box/raft.h
  test/replication-luatest/gh_6033_box_promote_demote_test.lua
  test/replication-luatest/gh_6860_election_off_demote_test.lua
  test/replication-luatest/gh_9855_box_ctl_demote_guarantee_demoting_test.lua
Labels: full-ci, static-build-ci

#10075 connpool: move source code file
  src/box/CMakeLists.txt
  src/box/lua/connpool.lua
  src/box/lua/init.c
Labels: full-ci

#10079 [backport 3.1] connpool: move source code file
  src/box/CMakeLists.txt
  src/box/lua/connpool.lua
  src/box/lua/init.c
Labels: full-ci
