Repository tarantool/tarantool, pull requests merged in 2024-08, with the labels that each got.

#10218 lua-yaml: wrap large doubles in quotes
  changelogs/unreleased/gh-10164-yaml-encoding-large-exps.md
  test/app-tap/lua/serializer_test.lua
  third_party/lua-yaml/lyaml.cc
Labels: full-ci

#10346 [backport 2.11] lua-yaml: wrap large doubles in quotes
  changelogs/unreleased/gh-10164-yaml-encoding-large-exps.md
  test/app-tap/lua/serializer_test.lua
  third_party/lua-yaml/lyaml.cc
Labels: full-ci

#10345 [backport 3.1] lua-yaml: wrap large doubles in quotes
  changelogs/unreleased/gh-10164-yaml-encoding-large-exps.md
  test/app-tap/lua/serializer_test.lua
  third_party/lua-yaml/lyaml.cc
Labels: full-ci

#10325 txn: first step towards cross-engine transactions
  src/box/box.cc
  src/box/engine.c
  src/box/engine.h
  src/box/errcode.h
  src/box/memtx_engine.cc
  src/box/txn.c
  src/box/txn.h
  src/box/vinyl.c
  test/box-luatest/gh_6150_memtx_tx_memory_monitoring_test.lua
  test/box/transaction.result
  test/sql/triggers.result
Labels: full-ci

#10355 box: don't require functional index function to be sandboxed
  changelogs/unreleased/gh-10349-func-index-without-sandbox.md
  src/box/alter.cc
  test/box-luatest/gh_10349_functional_index_without_sandbox_test.lua
  test/engine/func_index.result
  test/engine/func_index.test.lua
Labels: full-ci

#10321 datetime: fix values of unspecified fields in dt.parse()
  changelogs/unreleased/gh-8588-setting-unspecified-fields-fix.md
  src/lib/core/datetime.c
  test/app-tap/datetime.test.lua
Labels: full-ci

#10198 config: close old sockets after replacing socket
  changelogs/unreleased/gh-9535-close-listen-socket-after-replace.md
  src/box/lua/config/applier/console.lua
  test/config-luatest/console_test.lua
Labels: full-ci

#10372 [Backport 3.1] datetime: fix values of unspecified fields in dt.parse()
  changelogs/unreleased/gh-8588-setting-unspecified-fields-fix.md
  src/lib/core/datetime.c
  test/app-tap/datetime.test.lua
Labels: full-ci

#10371 [Backport 2.11] datetime: fix values of unspecified fields in dt.parse()
  changelogs/unreleased/gh-8588-setting-unspecified-fields-fix.md
  src/lib/core/datetime.c
  test/app-tap/datetime.test.lua
Labels: full-ci

#10381 [backport 3.1] config: close old socket after replacing socket
  changelogs/unreleased/gh-9535-close-listen-socket-after-replace.md
  src/box/lua/config/applier/console.lua
  test/config-luatest/console_test.lua
Labels: full-ci

#10297 refactor: use Lua C API instead of G(L)->gc.total
  src/box/lua/info.c
  src/box/lua/slab.cc
  src/lua/utils.c
  src/lua/utils.h
Labels: full-ci

#10379 vinyl: do not abort unrelated transactions on DDL
  changelogs/unreleased/gh-10375-vy-do-not-abort-unrelated-tx-on-ddl.md
  src/box/engine.h
  src/box/memtx_tx.c
  src/box/txn.c
  src/box/txn.h
  src/box/vinyl.c
  test/engine-luatest/gh_10375_ddl_does_not_abort_unrelated_transactions_test.lua
Labels: full-ci

#10389 [backport 3.1] refactor: use Lua C API instead of G(L)
  src/box/lua/info.c
  src/box/lua/slab.cc
  src/lua/utils.c
  src/lua/utils.h
Labels: full-ci

#10388 [backport 2.11] refactor: use Lua C API instead of G(L)
  src/box/lua/info.c
  src/box/lua/slab.cc
  src/lua/utils.c
  src/lua/utils.h
Labels: full-ci

#10227 serializer: remove duplicate of lua serializer
  src/box/lua/console.c
  src/box/lua/serialize_lua.c
  src/box/lua/serialize_lua.h
Labels: full-ci

#10394 [backport 3.1] serializer: remove duplicate of lua serializer
  src/box/lua/console.c
  src/box/lua/serialize_lua.c
  src/box/lua/serialize_lua.h
Labels: full-ci

#10395 [backport 2.11] serializer: remove duplicate of lua serializer
  src/box/lua/console.c
  src/box/lua/serialize_lua.c
  src/box/lua/serialize_lua.h
Labels: full-ci

#10387 build: show tzdata version in tarantool module
  CMakeLists.txt
  changelogs/unreleased/show-tzdata-version.md
  src/lua/init.c
  src/trivia/config.h.cmake
  src/version.c
  src/version.h
  test/app-tap/info.test.lua
Labels: full-ci

#10332 datetime: support tz field in :totable()
  changelogs/unreleased/gh-10331-tz-in-totable.md
  src/lua/datetime.lua
  test/app-tap/datetime.test.lua
  test/sql-luatest/datetime_test.lua
Labels: full-ci

#10402 [Backport 3.1] datetime: support tz field in :totable()
  changelogs/unreleased/gh-10331-tz-in-totable.md
  src/lua/datetime.lua
  test/app-tap/datetime.test.lua
  test/sql-luatest/datetime_test.lua
Labels: full-ci

#10348 datetime: test RFC 3339 and ISO 8601 formats
  test/app-luatest/datetime_test.lua
Labels: full-ci, datetime

#10248 box: grant/revoke user right after upgrade
  changelogs/unreleased/gh-9849-grant-revoke-user-right-after-upgrade.md
  src/box/lua/config/applier/credentials.lua
  test/config-luatest/upgrade_test.lua
Labels: full-ci

#10414 [backport 3.1] box: grant/revoke user rights after upgrade
  changelogs/unreleased/gh-9849-grant-revoke-user-right-after-upgrade.md
  src/box/lua/config/applier/credentials.lua
  test/config-luatest/upgrade_test.lua
Labels: full-ci

#10409 [Backport 2.11] datetime: test RFC 3339 and ISO 8601 formats
  test/app-luatest/datetime_test.lua
Labels: full-ci

#10410 [Backport 3.1] datetime: test RFC 3339 and ISO 8601 formats
  test/app-luatest/datetime_test.lua
Labels: full-ci

#10380 box: export more symbols
  extra/exports
  src/box/box.cc
  src/box/box.h
  src/box/lua/info.c
  test/box-luatest/gh_10378_export_symbols_test.lua
Labels: full-ci, 2.11

#10319 connpool: support filtering by `sharding.roles`
  changelogs/unreleased/gh-10318-connpool-sharding-roles-filter.md
  src/box/lua/connpool.lua
  test/config-luatest/rpc_test.lua
Labels: full-ci

#10421 box: account for `wait_ack` flag of the tx's last row during recovery
  changelogs/unreleased/gh-10412-box-begin-is-sync-async-commit-after-recovery.md
  src/box/box.cc
  test/box-luatest/gh_10412_box_begin_is_sync_async_commit_after_recovery_test.lua
Labels: full-ci

#10428 [backport 3.1] box: export more symbols
  extra/exports
  src/box/box.cc
  src/box/box.h
  src/box/lua/info.c
  test/box-luatest/gh_10378_export_symbols_test.lua
Labels: full-ci

#10435 [backport 3.1] box: account for `wait_ack` flag of the tx's last row during recovery
  changelogs/unreleased/gh-10412-box-begin-is-sync-async-commit-after-recovery.md
  src/box/box.cc
  test/box-luatest/gh_10412_box_begin_is_sync_async_commit_after_recovery_test.lua
Labels: full-ci

#10399 sql: fix use-after-poison in variable binding
  src/box/lua/execute.c
Labels: full-ci

#10439 [backport 3.1] sql: fix use-after-poison in variable binding
  src/box/lua/execute.c
Labels: full-ci

#10400 box: fix several gh-10088 corner cases
  src/box/applier.cc
  src/box/relay.cc
  test/replication-luatest/gh_10088_apply_deletion_of_replica_from_cluster_on_deleted_replica_test.lua
Labels: full-ci

#10324 config: grant access to specific function in config
  changelogs/unreleased/gh-10304-allow-specific-function-access.md
  src/box/lua/config/applier/credentials.lua
  src/box/lua/config/instance_config.lua
  test/config-luatest/instance_config_schema_test.lua
  test/config-luatest/privileges_test.lua
Labels: full-ci

#10353 box: drop iproto connections before client fibers on shutdown
  src/box/box.cc
  test/box-luatest/graceful_shutdown_test.lua
  test/box-luatest/shutdown_test.lua
Labels: full-ci

#10440 [backport 2.11] sql: fix use-after-poison in variable binding
  src/box/lua/execute.c
Labels: full-ci, do not merge

#10449 Change cmake variable BACKUP_STORAGE to option
  CMakeLists.txt
Labels: full-ci

#10431 Fixes required for using static build in OSS Fuzz
  test/fuzz/CMakeLists.txt
Labels: full-ci

#10453 [Backport 2.11] test/fuzz: update compiler and library flags
  test/fuzz/CMakeLists.txt
Labels: full-ci

#10454 [Backport 3.1] test/fuzz: update compiler and library flags
  test/fuzz/CMakeLists.txt
Labels: full-ci

#10418 config: fix replication.sync_timeout default value
  changelogs/unreleased/gh-10280-fix-replication-sync-timeout-default-value.md
  src/box/lua/config/instance_config.lua
  test/config-luatest/cluster_config_schema_test.lua
  test/config-luatest/gh_10280_replication_sync_timeout_default_value_test.lua
  test/config-luatest/instance_config_schema_test.lua
Labels: full-ci

#10457 [backport 3.1] config: fix replication.sync_timeout default value
  changelogs/unreleased/gh-10280-fix-replication-sync-timeout-default-value.md
  src/box/lua/config/instance_config.lua
  test/config-luatest/cluster_config_schema_test.lua
  test/config-luatest/gh_10280_replication_sync_timeout_default_value_test.lua
  test/config-luatest/instance_config_schema_test.lua
Labels: full-ci

#10451 memtx: do not pass pagination key to MVCC
  changelogs/unreleased/gh-10488-pagination-mvcc-non-unique-index.md
  src/box/memtx_tree.cc
  test/box-luatest/gh_10448_pagination_mvcc_non_unique_index_test.lua
Labels: full-ci

#10455 test: fix flaky gh-5998-one-tx-for-ddl.test.lua
  test/box/gh-5998-one-tx-for-ddl.result
  test/box/gh-5998-one-tx-for-ddl.test.lua
Labels: full-ci

#10456 memtx: skip excluded tuples in index count with MVCC enabled
  changelogs/unreleased/gh-10396-memtx-mvcc-exclude-null-count.md
  src/box/memtx_tx.c
  test/box-luatest/gh_9954_mvcc_with_exclude_null_test.lua
Labels: full-ci

#10083 box: store space name and engine name in `index_def` for error reporting
  perf/memtx.cc
  src/box/alter.cc
  src/box/index.cc
  src/box/index_def.c
  src/box/index_def.h
  src/box/key_list.c
  src/box/schema.cc
  src/box/sql.c
  src/box/sql/build.c
  src/box/sql/where.c
  src/box/vinyl.c
  test/unit/vy_point_lookup.c
Labels: full-ci

#10469 vinyl: enable exact match optimization for unique secondary indexes
  changelogs/unreleased/gh-10442-vy-exact-match-optimization.md
  src/box/vy_read_iterator.c
  src/box/vy_read_iterator.h
  src/box/vy_stmt.c
  src/box/vy_stmt.h
  test/vinyl-luatest/gh_10442_exact_match_optimization_test.lua
Labels: full-ci

#10466 [backport 2.11] memtx: do not pass pagination key to MVCC
  changelogs/unreleased/gh-10488-pagination-mvcc-non-unique-index.md
  src/box/memtx_tree.cc
  test/box-luatest/gh_10448_pagination_mvcc_non_unique_index_test.lua
Labels: full-ci

#10465 [backport 3.1] memtx: do not pass pagination key to MVCC
  changelogs/unreleased/gh-10488-pagination-mvcc-non-unique-index.md
  src/box/memtx_tree.cc
  test/box-luatest/gh_10448_pagination_mvcc_non_unique_index_test.lua
Labels: full-ci

#10471 vinyl: do not discard run on dump/compaction abort if index was dropped
  changelogs/unreleased/gh-10452-vy-log-discard-run-after-index-drop-fix.md
  src/box/vy_scheduler.c
  test/vinyl-luatest/gh_10452_discard_run_after_index_drop_test.lua
Labels: full-ci

#10472 [release/3.1] Generate changelog for 3.1.2
  changelogs/3.1.2.md
  changelogs/unreleased/gh-10164-yaml-encoding-large-exps.md
  changelogs/unreleased/gh-10199-luajit-fixes.md
  changelogs/unreleased/gh-10280-fix-replication-sync-timeout-default-value.md
  changelogs/unreleased/gh-10331-tz-in-totable.md
  changelogs/unreleased/gh-10374-timestamp-in-totable.md
  changelogs/unreleased/gh-10375-vy-do-not-abort-unrelated-tx-on-ddl.md
  changelogs/unreleased/gh-10396-memtx-mvcc-exclude-null-count.md
  changelogs/unreleased/gh-10412-box-begin-is-sync-async-commit-after-recovery.md
  changelogs/unreleased/gh-10442-vy-exact-match-optimization.md
  changelogs/unreleased/gh-10452-vy-log-discard-run-after-index-drop-fix.md
  changelogs/unreleased/gh-10488-pagination-mvcc-non-unique-index.md
  changelogs/unreleased/gh-8588-setting-unspecified-fields-fix.md
  changelogs/unreleased/gh-9535-close-listen-socket-after-replace.md
  changelogs/unreleased/gh-9849-grant-revoke-user-right-after-upgrade.md
  src/box/lua/upgrade.lua
Labels: full-ci

#10302 box: filter out tmp and remote txs when aborting all txs for DDL
  changelogs/unreleased/gh-9720-tmp-spaces-ddl-abort-applier-txs.md
  src/box/memtx_space.c
  src/box/memtx_tx.c
  src/box/txn.c
  src/box/txn.h
  src/box/vinyl.c
  src/lib/core/errinj.h
  test/replication-luatest/gh_9720_tmp_spaces_ddl_abort_applier_txs_test.lua
Labels: full-ci

#10309 test: fix gh-5430 test
  src/box/box.cc
  test/replication/gh-5430-cluster-mvcc.result
  test/replication/gh-5430-cluster-mvcc.test.lua
Labels: full-ci

#10408 refactor: rename test function in gh_8252 with luatest requirements
  test/app-luatest/gh_8252_jit_off_on_macOS_by_default_test.lua
Labels: osx, full-ci

#10139 Implement logarithmic `index:count` in the memtx tree
  src/box/memtx_tree.cc
  src/box/memtx_tx.c
  src/box/memtx_tx.h
  test/box-luatest/gh_8204_fast_offset_test.lua
Labels: full-ci

#10492 [backport 2.11] test: add test_ prefix to a function name
  test/app-luatest/gh_8252_jit_off_on_macOS_by_default_test.lua
Labels: osx, full-ci

#10493 [backport 3.2] test: add test_ prefix to a function name
  test/app-luatest/gh_8252_jit_off_on_macOS_by_default_test.lua
Labels: osx, full-ci
