Repository tarantool/tarantool, pull requests merged in 2024-04, with the labels that each got.

#9899 config: add failover stateboard options
  src/box/lua/config/instance_config.lua
  test/config-luatest/cluster_config_schema_test.lua
  test/config-luatest/instance_config_schema_test.lua
Labels: full-ci

#9902 config: introduce config:instance_uri()
  changelogs/unreleased/gh-9842-instance-uri.md
  src/box/lua/config/configdata.lua
  src/box/lua/config/init.lua
  test/config-luatest/cluster_config_test.lua
Labels: full-ci

#9890 httpc: HTTP version option for HTTP client
  changelogs/unreleased/gh-9806-http-set-version.md
  src/httpc.c
  src/httpc.h
  src/lua/httpc.c
  src/lua/httpc.lua
  test/app-luatest/http_client_http_version_test.lua
Labels: full-ci

#9911 net.replicaset: fix a flaky test
  test/box-luatest/gh_9823_net_replicaset_test.lua
Labels: full-ci

#9919 ci: don't send coverage results for submodules
  .github/workflows/coverage.yml
Labels: full-ci

#9297 box: fix memory leak when dropping temporary spaces
  changelogs/unreleased/gh-9296-fix-memory-leak-when-dropping-fully-temporary-spaces.md
  src/box/txn.c
  src/box/txn.h
  test/box-luatest/fully-temporary_spaces_test.lua
Labels: full-ci

#9928 box: add error field 'name' with name corresponding to code
  changelogs/unreleased/gh-9875-add-client-error-name.md
  src/box/error.cc
  src/box/lua/error.cc
  test/app-luatest/msgpack_test.lua
  test/app/fiber.result
  test/box-luatest/error_subsystem_improvements_test.lua
  test/box/error.result
  test/engine/func_index.result
  test/unit/error.c
  test/unit/mp_error.cc
Labels: full-ci

#9941 [backport 3.0] box: fix memory leak when dropping temporary spaces
  changelogs/unreleased/gh-9296-fix-memory-leak-when-dropping-fully-temporary-spaces.md
  src/box/txn.c
  src/box/txn.h
  test/box-luatest/fully-temporary_spaces_test.lua
Labels: full-ci

#9942 connpool: fix connection error description
  src/box/lua/experimental/connpool.lua
  test/config-luatest/rpc_test.lua
Labels: full-ci

#9931 Introduce `mode` option for `call()` and `filter()` from `experimental.connpool` module
  changelogs/unreleased/gh-9930-mode-option.md
  src/box/lua/experimental/connpool.lua
  test/config-luatest/rpc_test.lua
Labels: full-ci

#9945 connpool: instances, replicasets and groups filter
  src/box/lua/experimental/connpool.lua
  test/config-luatest/rpc_test.lua
Labels: full-ci

#9948 [backport 3.0] trigger: do not return handler from trigger.del
  src/box/lua/trigger.c
  test/app-luatest/trigger_module_test.lua
Labels: full-ci

#9947 build: use VK S3 for icu4c and zziplib archives
  cmake/BuildICU.cmake
  cmake/BuildZZIP.cmake
Labels: static-build-ci

#9950 [backport 3.0] build: use VK S3 for icu4c and zziplib archives
  cmake/BuildICU.cmake
  cmake/BuildZZIP.cmake
Labels: static-build-ci

#9951 [backport 2.11] build: use VK S3 for icu4c and zziplib archives
  cmake/BuildICU.cmake
  cmake/BuildZZIP.cmake
Labels: static-build-ci

#9693 ci: add timeout for workflows
  .github/workflows/codeql.yml
  .github/workflows/coverage.yml
  .github/workflows/coverity.yml
  .github/workflows/debug.yml
  .github/workflows/debug_aarch64.yml
  .github/workflows/debug_asan_clang.yml
  .github/workflows/default_gcc_centos_7.yml
  .github/workflows/docker_build_push.yml
  .github/workflows/etcd_integration.yml
  .github/workflows/freebsd.yml
  .github/workflows/fuzzing.yml
  .github/workflows/lango-stale-reviews.yml
  .github/workflows/lint.yml
  .github/workflows/luajit-integration.yml
  .github/workflows/memtx_allocator_based_on_malloc.yml
  .github/workflows/osx.yml
  .github/workflows/out_of_source.yml
  .github/workflows/packaging_build_test_deploy.yml
  .github/workflows/perf_micro.yml
  .github/workflows/publish-module-api-doc.yaml
  .github/workflows/release.yml
  .github/workflows/release_asan_clang.yml
  .github/workflows/release_clang.yml
  .github/workflows/release_lto.yml
  .github/workflows/release_lto_clang.yml
  .github/workflows/reusable_build.yml
  .github/workflows/source.yml
  .github/workflows/static_build.yml
  .github/workflows/static_build_cmake_linux.yml
  .github/workflows/submodule_update.yml
Labels: full-ci

#9955 memtx: fix a bug with mvcc and exclude_null option
  changelogs/unreleased/gh-9954-mvcc-crash-with-exclude-null.md
  src/box/memtx_tx.c
  test/box-luatest/gh_9954_mvcc_with_exclude_null_test.lua
Labels: full-ci, 2.10

#9957 [Backport 2.11] memtx: fix a bug with mvcc and exclude_null option
  changelogs/unreleased/gh-9954-mvcc-crash-with-exclude-null.md
  src/box/memtx_tx.c
  test/box-luatest/gh_9954_mvcc_with_exclude_null_test.lua
Labels: full-ci

#9958 [Backport 2.10] memtx: fix a bug with mvcc and exclude_null option
  changelogs/unreleased/gh-9954-mvcc-crash-with-exclude-null.md
  src/box/memtx_tx.c
  test/box-luatest/gh_9954_mvcc_with_exclude_null_test.lua
Labels: full-ci

#9676 netbox: close transport after stopping worker loop and wait for the stop
  changelogs/unreleased/gh-9621-netbox-worker-crash.md
  changelogs/unreleased/gh-9826-netbox-on_schema_reload-close.md
  src/box/lua/net_box.c
  test/app-luatest/gh_9621_netbox_worker_crash_test.lua
  test/box-luatest/gh_9826_netbox_on_schema_reload_close_test.lua
  test/box-luatest/net_box_test.lua
Labels: full-ci

#9971 test: fix flaky persistent triggers test
  test/box-luatest/gh_8663_persistent_triggers_test.lua
Labels: full-ci

#9974 [backport 3.1] test: fix flaky persistent triggers test
  test/box-luatest/gh_8663_persistent_triggers_test.lua
Labels: full-ci

#7648 popen: add timeout for :wait()
  changelogs/unreleased/popen-wait-after-close.md
  changelogs/unreleased/popen-wait-busy-loop.md
  changelogs/unreleased/popen-wait-timeout.md
  src/lib/core/popen.c
  src/lib/core/popen.h
  src/lua/popen.c
  test/app-luatest/popen_wait_test.lua
  test/app-tap/popen.test.lua
Labels: full-ci

#9969 [2.10] ci: add timeouts for workflow jobs
  .github/workflows/alpine_3_16.yml
  .github/workflows/alpine_3_16_aarch64.yml
  .github/workflows/centos_7.yml
  .github/workflows/centos_7_aarch64.yml
  .github/workflows/centos_8.yml
  .github/workflows/centos_8_aarch64.yml
  .github/workflows/coverage.yml
  .github/workflows/coverity.yml
  .github/workflows/debian_10.yml
  .github/workflows/debian_10_aarch64.yml
  .github/workflows/debian_11.yml
  .github/workflows/debian_11_aarch64.yml
  .github/workflows/debian_9.yml
  .github/workflows/debug.yml
  .github/workflows/debug_aarch64.yml
  .github/workflows/debug_asan_clang.yml
  .github/workflows/default_gcc_centos_7.yml
  .github/workflows/fedora_34.yml
  .github/workflows/fedora_34_aarch64.yml
  .github/workflows/fedora_35.yml
  .github/workflows/fedora_35_aarch64.yml
  .github/workflows/fedora_36.yml
  .github/workflows/fedora_36_aarch64.yml
  .github/workflows/freebsd.yml
  .github/workflows/fuzzing.yml
  .github/workflows/lint.yml
  .github/workflows/luajit-integration.yml
  .github/workflows/memtx_allocator_based_on_malloc.yml
  .github/workflows/osx.yml
  .github/workflows/out_of_source.yml
  .github/workflows/redos_7_3.yaml
  .github/workflows/release.yml
  .github/workflows/release_asan_clang.yml
  .github/workflows/release_clang.yml
  .github/workflows/release_lto.yml
  .github/workflows/release_lto_clang.yml
  .github/workflows/reusable_build.yml
  .github/workflows/source.yml
  .github/workflows/static_build.yml
  .github/workflows/static_build_cmake_linux.yml
  .github/workflows/submodule_update.yml
  .github/workflows/ubuntu_16_04.yml
  .github/workflows/ubuntu_18_04.yml
  .github/workflows/ubuntu_20_04.yml
  .github/workflows/ubuntu_20_04_aarch64.yml
  .github/workflows/ubuntu_22_04.yml
  .github/workflows/ubuntu_22_04_aarch64.yml
Labels: full-ci

#9963 replication: recovering from long WAL
  changelogs/unreleased/gh-9094-timeout-on-too-big-xlog-subscribe.md
  src/box/relay.cc
  src/lib/core/errinj.h
  test/box/errinj.result
  test/replication-luatest/gh_9094_long_wal_subscribe_test.lua
Labels: full-ci
