Repository tarantool/tarantool, pull requests merged in 2024-02, with the labels that each got.

#9627 gc: add graceful shutdown
  src/box/box.cc
  src/box/gc.c
  src/box/gc.h
  src/box/memtx_engine.cc
  src/lib/core/errinj.h
  test/app-luatest/shutdown_test.lua
  test/box/errinj.result
Labels: full-ci

#9642 box: fix hot standby shutdown hang
  src/box/box.cc
  test/app-luatest/shutdown_test.lua
Labels: full-ci

#9647 build: fix static build error when compiling with Clang
  cmake/CheckDependencies.cmake
  cmake/compiler.cmake
Labels: full-ci

#9623 config: call extras.post_apply() if reload failed
  src/box/lua/config/init.lua
  test/config-luatest/basic_test.lua
Labels: full-ci

#9526 test: cover cluster upgrade with vshard
  test/box-luatest/upgrade/2.11.0/vshard/instance-001/00000000000000003049.snap
  test/box-luatest/upgrade/2.11.0/vshard/instance-002/00000000000000003049.snap
  test/box-luatest/upgrade/2.11.0/vshard/instance-003/00000000000000003049.snap
  test/box-luatest/upgrade/2.11.0/vshard/instance-004/00000000000000003049.snap
  test/box-luatest/upgrade/2.11.0/vshard/storage-gen.lua
  test/config-luatest/vshard_upgrade_test.lua
Labels: full-ci

#9653 [backport 3.0] config: call extras.post_apply() if reload failed
  src/box/lua/config/init.lua
  test/config-luatest/basic_test.lua
Labels: full-ci

#9655 [backport 3.0] test: cover cluster upgrade with vshard
  test/box-luatest/upgrade/2.11.0/vshard/instance-001/00000000000000003049.snap
  test/box-luatest/upgrade/2.11.0/vshard/instance-002/00000000000000003049.snap
  test/box-luatest/upgrade/2.11.0/vshard/instance-003/00000000000000003049.snap
  test/box-luatest/upgrade/2.11.0/vshard/instance-004/00000000000000003049.snap
  test/box-luatest/upgrade/2.11.0/vshard/storage-gen.lua
  test/config-luatest/vshard_upgrade_test.lua
Labels: full-ci

#9651 config: move role start and stop to _post_apply()
  changelogs/unreleased/gh-9649-config-get-in-roles.md
  src/box/lua/config/applier/roles.lua
  test/config-luatest/roles_test.lua
Labels: full-ci

#9636 Once again fix transaction boundaries in replication for txs ending with a local row
  changelogs/unreleased/gh-9491-last-local-row-tx-boundary.md
  src/box/recovery.cc
  test/replication-luatest/gh_9491_local_space_tx_boundary_test.lua
Labels: full-ci

#9660 [backport 3.0] config: move role start and stop to _post_apply()
  changelogs/unreleased/gh-9649-config-get-in-roles.md
  src/box/lua/config/applier/roles.lua
  test/config-luatest/roles_test.lua
Labels: full-ci

#9661 config: introduce sharding.rebalancer_mode
  changelogs/unreleased/gh-9657-option-rebalancer_mode.md
  src/box/lua/config/configdata.lua
  src/box/lua/config/instance_config.lua
  test/config-luatest/cluster_config_schema_test.lua
  test/config-luatest/instance_config_schema_test.lua
  test/config-luatest/vshard_test.lua
Labels: full-ci

#9668 [backport 3.0] Once again fix transaction boundaries in replication for txs ending with a local row
  changelogs/unreleased/gh-9491-last-local-row-tx-boundary.md
  src/box/recovery.cc
  test/replication-luatest/gh_9491_local_space_tx_boundary_test.lua
Labels: full-ci

#9667 [backport 2.11] Once again fix transaction boundaries in replication for txs ending with a local row
  changelogs/unreleased/gh-9491-last-local-row-tx-boundary.md
  src/box/recovery.cc
  test/replication-luatest/gh_9491_local_space_tx_boundary_test.lua
Labels: full-ci

#9669 [backport 2.10] Once again fix transaction boundaries in replication for txs ending with a local row
  changelogs/unreleased/gh-9491-last-local-row-tx-boundary.md
  src/box/recovery.cc
  test/replication-luatest/gh_9491_local_space_tx_boundary_test.lua
Labels: full-ci

#9654 key_def: ignore json path in `key_def_find_by_fieldno`
  src/box/key_def.c
  src/box/key_def.h
  test/unit/key_def.cc
Labels: full-ci

#9674 [backport 3.0] key_def: ignore json path in key_def_find_by_fieldno
  src/box/key_def.c
  src/box/key_def.h
  test/unit/key_def.cc
Labels: full-ci

#9673 [backport 2.11] key_def: ignore json path in key_def_find_by_fieldno
  src/box/key_def.c
  src/box/key_def.h
  test/unit/key_def.c
Labels: full-ci

#9663 build: fix package.cpath for debian based distros
  CMakeLists.txt
  changelogs/unreleased/gh-9580-fix-cpath-for-external-libs.md
Labels: full-ci

#9692 [3.0] build: fix package.cpath for Debian based distros
  CMakeLists.txt
  changelogs/unreleased/gh-9580-fix-cpath-for-external-libs.md
Labels: full-ci

#8752 gdb: support msgpack extension MP_TUPLE
  tools/tarantool-gdb.py
Labels: devtools, 3.0

#9681 box/lua: allow to set custom error payload fields
  changelogs/unreleased/gh-9104-allow-to-set-error-payload.md
  src/box/lua/error.cc
  test/box-luatest/error_subsystem_improvements_test.lua
Labels: full-ci

#9707 ci: fix integration concurrency group
  .github/workflows/integration.yml
Labels: full-ci

#9695 lua: add `message` argument to table constructor of `box.error.new`
  changelogs/unreleased/gh-9102-error-new-message-arg.md
  src/box/lua/error.cc
  test/box-luatest/error_subsystem_improvements_test.lua
Labels: full-ci

#9704 vinyl: check if fiber is cancelled after tasks completion
  src/box/vy_scheduler.c
Labels: full-ci

#9697 lua: fix memory leak in `error_object:set_prev()`
  changelogs/unreleased/gh-9694-memory-leak-in-error_object-set_prev.md
  src/lua/error.lua
Labels: full-ci

#9699 [2.11] ci: add `Fedora 39`
  .github/workflows/fedora_39.yml
  .github/workflows/fedora_39_aarch64.yml
Labels: full-ci

#9691 config: fix wrong status after setting permissions
  src/box/lua/config/applier/credentials.lua
  src/box/lua/config/utils/aboard.lua
  test/config-luatest/credentials_applier_test.lua
Labels: full-ci

#9708 [backport 3.0] lua: fix memory leak in `error_object:set_prev()`
  changelogs/unreleased/gh-9694-memory-leak-in-error_object-set_prev.md
  src/lua/error.lua
Labels: full-ci

#9709 [backport 2.11] lua: fix memory leak in `error_object:set_prev()`
  changelogs/unreleased/gh-9694-memory-leak-in-error_object-set_prev.md
  src/lua/error.lua
Labels: full-ci

#9701 app: shutdown fiber creating snapshot triggered by signal
  src/box/box.cc
  src/box/box.h
  src/main.cc
  test/box-luatest/shutdown_test.lua
Labels: full-ci

#9711 [backport 3.0] config: fix wrong status after setting permissions
  src/box/lua/config/applier/credentials.lua
  src/box/lua/config/utils/aboard.lua
  test/config-luatest/credentials_applier_test.lua
Labels: full-ci

#8534 datetime: fix strptime for fuzzer
  changelogs/unreleased/gh-8525-strptime-fix.md
  src/lib/tzcode/strptime.c
  test/static/corpus/datetime_strptime/clusterfuzz-6575551489114112
Labels: full-ci

#9710 box/lua: allow to set error cause via `prev` argument
  changelogs/unreleased/gh-9103-error-new-prev-arg.md
  src/box/lua/error.cc
  test/box-luatest/error_subsystem_improvements_test.lua
Labels: full-ci

#9715 fiber: allow creating system fibers during shutdown
  src/box/box.cc
  src/lib/core/fiber.c
  test/unit/fiber.cc
  test/vinyl-luatest/shutdown_test.lua
Labels: full-ci

#9690 misc: cleanup usage of pthread_cancel
  asan/asan.supp
  asan/lsan.supp
  src/box/wal.c
  src/lib/core/cbus.c
  src/lib/core/fiber.c
  src/lib/core/fiber.h
  src/tt_pthread.h
  test/box-luatest/gh_3211_per_module_log_level_test.lua
  test/unit/CMakeLists.txt
  test/unit/cbus_hang.c
  test/unit/cbus_hang.result
  test/unit/fiber.cc
  test/unit/fiber.result
Labels: full-ci, asan-ci

#9718 iproto: fix assertion on dropping of a new connection
  changelogs/unreleased/gh-9717-fix-crash-on-new-connection-drop.md
  src/box/iproto.cc
  test/box-luatest/shutdown_test.lua
Labels: full-ci

#9725 build/lua: add TEST_BUILD define/tarantool.build flag
  CMakeLists.txt
  changelogs/unreleased/add-test-build-flag-to-tarantool-build.md
  src/lua/init.c
  src/trivia/config.h.cmake
  test/app-luatest/tarantool_package_test.lua
Labels: full-ci

#9744 alter: move format compatibility check to `space_check_format`
  src/box/alter.cc
  src/box/memtx_space.c
  src/box/vinyl.c
Labels: full-ci

#9726 Remove LuaJIT-related CLI tests
  test/box-py/args.result
  test/box-py/args.test.py
Labels: full-ci

#9733 cmake: add libresolv to static dependency list
  cmake/CheckDependencies.cmake
  src/CMakeLists.txt
Labels: full-ci
