Repository tarantool/tarantool, pull requests merged in 2025-07, with the labels that each got.

#11593 box: fix crash while nil-uuid subscribe request
  changelogs/unreleased/gh-11531-crash-in-anon-subscribe-request-with-nil-id.md
  src/box/box.cc
  test/box-luatest/gh_10155_make_iproto_resistant_to_misusage_test.lua
  test/replication-luatest/gh_11531_crash_in_anonymous_subscribe_request_test.lua
  test/replication-luatest/persistent_gc_anon_test.lua
Labels: backport/3.2, backport/3.3, backport/3.4

#11659 box: do not normalize `covers` twice on index alter
  src/box/lua/schema.lua
Labels: full-ci, 3.4

#11666 [backport 3.3] ci: replace debian-buster by debian-bookworm
  .github/workflows/distrib.yml
Labels: full-ci

#11584 config: add `include` field for config files
  changelogs/unreleased/gh-11583-config-files-include.md
  src/box/lua/config/cluster_config.lua
  src/box/lua/config/descriptions.lua
  src/box/lua/config/instance_config.lua
  src/box/lua/config/source/file.lua
  src/box/lua/config/utils/file.lua
  test/config-luatest/cluster_config_schema_test.lua
  test/config-luatest/config_include_test.lua
Labels: full-ci

#11699 box: fix misleading errors on privilege revoke from admin
  changelogs/unreleased/gh-11526-misleading-admin-priv-revoke-error.md
  src/box/lua/schema.lua
  test/box-luatest/gh_11526_misleading_privilege_error_test.lua
Labels: backport/3.2, backport/3.3, backport/3.4

#11713 WAL queue invalid previous entry fix
  src/box/journal.c
  test/box-luatest/gh_11180_wal_spurious_wakeup_test.lua
Labels: backport/3.2, backport/3.3, backport/3.4

#10747 box: allow to access to the granted role in _vuser space
  changelogs/unreleased/gh-10057-box-schema-user-info.md
  src/box/sysview.c
  src/box/user.cc
  src/box/user.h
  test/box-luatest/gh_10057_user_role_test.lua
Labels: full-ci, backport/3.2, backport/3.3, backport/3.4
