Repository tarantool/tarantool, pull requests merged in 2025-02, with the labels that each got.

#11077 test/static: remove dictionaries
  test/static/datetime_parse_full_fuzzer.dict
  test/static/datetime_strptime_fuzzer.dict
  test/static/swim_proto_member_fuzzer.dict
  test/static/swim_proto_meta_fuzzer.dict
Labels: full-ci

#11080 ci: update path whitelist in a fuzzing workflow
  .github/workflows/fuzzing.yml
Labels: full-ci

#11073 netbox: fix in-progress request counter underflow during schema fetch
  changelogs/unreleased/gh-11062-net-box-fetch-schema-restart-fix.md
  src/box/lua/net_box.c
  test/box-luatest/gh_11062_net_box_fetch_schema_restart_test.lua
Labels: full-ci

#11072 config: allow failover only in the global scope
  changelogs/unreleased/config-failover-section-in-global-scope.md
  src/box/lua/config/instance_config.lua
  src/box/lua/config/validators.lua
  test/config-luatest/cluster_config_schema_test.lua
Labels: full-ci, backport/3.2, backport/3.3

#11007 memtx: finalize prepare of all transactions in memtx MVCC
  changelogs/unreleased/gh-10715-memtx-mvcc-conflict-with-prepared-sysview-txn.md
  src/box/memtx_engine.cc
  src/box/memtx_tx.c
  src/box/memtx_tx.h
  src/box/txn.c
  test/box-luatest/gh_10715_memtx_mvcc_conflict_with_prepared_sysview_txn_test.lua
Labels: full-ci

#11082 box: fix WAL queue size accounting on errors
  changelogs/unreleased/gh-11081-fix-wal-queue-size-accounting.md
  src/box/journal.h
  test/box-luatest/gh_11081_wal_queue_size_accounting_test.lua
Labels: full-ci

#11093 test: stabilize engine/errinj_ddl test
  test/engine/errinj_ddl.result
  test/engine/errinj_ddl.test.lua
  test/engine/suite.ini
Labels: full-ci, backport/2.11, backport/3.2, backport/3.3

#11103 test: stabilize replication/sync test
  test/replication/suite.ini
  test/replication/sync.result
  test/replication/sync.test.lua
Labels: full-ci, backport/2.11, backport/3.2, backport/3.3

#11090 [backport 3.3] config: allow failover only in the global scope
  changelogs/unreleased/config-failover-section-in-global-scope.md
  src/box/lua/config/instance_config.lua
  test/config-luatest/cluster_config_schema_test.lua
Labels: full-ci

#11089 [backport 3.2] config: allow failover only in the global scope
  changelogs/unreleased/config-failover-section-in-global-scope.md
  src/box/lua/config/instance_config.lua
  test/config-luatest/cluster_config_schema_test.lua
Labels: full-ci

#11104 txn: do not rollback transaction statements on timeout
  changelogs/unreleased/gh-11088-vy-tx-crash-on-timeout-fix.md
  src/box/txn.c
  test/vinyl-luatest/gh_11088_tx_abort_on_timeout_test.lua
Labels: full-ci

#11114 [backport 2.11] test: stabilize replication/sync test
  test/replication/suite.ini
  test/replication/sync.result
  test/replication/sync.test.lua
Labels: full-ci

#10952 log: fix truncating log message to 1024 bytes in 'json' log
  changelogs/unreleased/gh-10918-fix-log-message-truncate.md
  src/lib/core/say.c
  src/lib/core/util.c
  src/trivia/util.h
  test/app-tap/logger.test.lua
Labels: full-ci, backport/2.11, backport/3.2, backport/3.3

#11143 [backport 2.11] log: fix truncating log message to 1024 bytes in 'json' log
  changelogs/unreleased/gh-10918-fix-log-message-truncate.md
  src/lib/core/say.c
  src/lib/core/util.c
  src/trivia/util.h
  test/app-tap/logger.test.lua
Labels: full-ci

#11123 perf: fix a clang warning for BPS tree perftest
  perf/bps_tree.cc
Labels: full-ci, backport/3.2, backport/3.3

#11013 connpool: add internal pool class
  src/box/lua/connpool.lua
Labels: full-ci

#11092 relay: fix synchro queue limitation after a local recovery
  changelogs/unreleased/gh-11091-synchro-queue-is-unlimited-after-local-recovery.md
  src/box/box.cc
  test/replication-luatest/gh_7486_replication_synchro_queue_max_size_test.lua
Labels: backport/3.3

#11159 ci: deploy Ubuntu Noble (24.04) packages
  .github/workflows/ubuntu_24_04.yml
  .github/workflows/ubuntu_24_04_aarch64.yml
  changelogs/unreleased/add-ubuntu-noble.md
Labels: full-ci

#11153 config: add test for iproto.listen removal
  test/config-luatest/iproto_listen_test.lua
Labels: full-ci

#11168 vinyl: don't create cache chain over unconfirmed deferred DELETE
  changelogs/unreleased/gh-11140-vy-deferred-delete-rollback-fix.md
  src/box/vy_read_iterator.c
  test/vinyl-luatest/gh_11140_deferred_delete_rollback_test.lua
Labels: full-ci

#11154 config: drop JSONification from the log wrapper
  src/box/lua/config/utils/log.lua
  test/config-luatest/log_wrapper_test.lua
Labels: full-ci

#11181 vinyl: fix race between manual compaction and range splitting
  src/box/vy_lsm.c
Labels: full-ci

#11189 vinyl: fix gc of incomplete runs left after dropped space
  changelogs/unreleased/gh-11163-vy-incomplete-run-gc-fix.md
  src/box/vinyl.c
  src/box/vy_scheduler.c
  test/vinyl-luatest/gh_11163_gc_while_compaction_in_progress_test.lua
Labels: full-ci

#11200 ci: verify the downgrade list before the release
  .github/workflows/downgrade_versions.yml
  tools/check-downgrade-versions.sh
Labels: backport/2.11, backport/3.2, backport/3.3

#11205 txn: do not call engine rollback_statement if begin_statement failed
  src/box/txn.c
  test/box-luatest/cross_engine_tx_test.lua
Labels: full-ci

#11196 changelog: apply suggestions from @lenkis
  changelogs/unreleased/gh-9965-wrong-numbers-comparison.md
Labels: backport/3.2, backport/3.3

#11209 [backport 3.2] upgrade: add 2.11.6 to the downgrade version list
  src/box/lua/upgrade.lua
Labels: full-ci

#11195 ci: use AWS CLI v2.22.35
  .github/workflows/source.yml
Labels: backport/2.11, backport/3.2, backport/3.3

#11183 box: introduce index covers option
  src/box/alter.cc
  src/box/index_def.c
  src/box/index_def.h
  src/box/lua/schema.lua
  src/box/lua/space.cc
  src/box/memtx_space.c
  src/box/vinyl.c
  src/trivia/util.h
  test/box-luatest/index_covers_test.lua
Labels: full-ci

#11214 test/vinyl/select_consistency: make garbage check more robust
  test/vinyl-luatest/select_consistency_test.lua
Labels: full-ci
