Repository tarantool/tarantool, pull requests merged in 2025-03, with the labels that each got.

#10782 fuzz: setup memcs fuzzing
  test/fuzz/lua/test_engine.lua
Labels: full-ci

#10761 config/schema: transform composite types in :map()
  changelogs/unreleased/config-transform-composite-type.md
  src/box/lua/config/utils/schema.lua
  test/config-luatest/schema_test.lua
Labels: full-ci

#11151 config: structurize applier/box_cfg
  src/box/lua/config/applier/box_cfg.lua
Labels: full-ci

#11241 box: call destroy callback for stmt on rollback trigger
  src/box/txn.c
  src/box/txn.h
Labels: full-ci

#11175 lua: rewrite `tuple_field_by_path()` in FFI
  src/box/lua/tuple.c
  src/box/lua/tuple.lua
Labels: refactoring, performance, full-ci

#11244 config: remove tricks around non-scalar defaults
  src/box/lua/config/applier/box_cfg.lua
  src/box/lua/config/instance_config.lua
Labels: full-ci

#11252 vinyl: fix space truncation being aborted by yield under load
  changelogs/unreleased/gh-11249-vy-space-truncate-under-load-fix.md
  src/box/vy_tx.c
  test/engine-luatest/gh_11249_space_truncate_under_load_test.lua
Labels: full-ci

#11210 tools: update release notes template
  tools/gen-release-notes
Labels: backport/2.11, backport/3.2, backport/3.3

#11260 config: don't choose learners as bootstrap leaders
  changelogs/unreleased/gh-10842-learners-not-bootstrap-leaders.md
  src/box/lua/config/applier/box_cfg.lua
  src/box/lua/config/configdata.lua
  test/config-luatest/failover_learners_test.lua
Labels: full-ci

#11271 config: call roles `stop` callback on shutdown
  changelogs/unreleased/gh-10795-role-stop-on-shutdown.md
  src/box/lua/config/applier/roles.lua
  test/config-luatest/roles_test.lua
Labels: full-ci

#11290 xrow: add missing break statement
  src/box/xrow.c
Labels: code health

#11275 config: add API to test if role is set for instance
  changelogs/unreleased/gh-11288-enabled-roles-api.md
  src/box/lua/config/init.lua
  test/config-luatest/roles_test.lua
  test/config-luatest/vshard_test.lua
Labels: full-ci

#11298 config: apply lua_call privileges before bootstrap
  changelogs/unreleased/lua-call-runtime-priv-before-bootstrap.md
  src/box/lua/config/init.lua
  test/config-luatest/runtime_priv_test.lua
Labels: full-ci, backport/3.3

#11297 vinyl: do not reset cache link LSN on partial key lookup
  changelogs/unreleased/gh-11079-vy-cache-read-view-fix.md
  src/box/vy_cache.c
  test/vinyl-luatest/gh_11079_invisible_delete_caching_test.lua
Labels: full-ci

#11074 gc: use *.snap st_mtime to schedule after restart
  changelogs/unreleased/gh-9820-checkpoint-interval-after-restart.md
  src/box/checkpoint_schedule.c
  src/box/checkpoint_schedule.h
  src/box/gc.c
  src/box/gc.h
  src/box/memtx_engine.cc
  test/box-luatest/gh_9820_checkpoint_interval_after_restart_test.lua
  test/unit/checkpoint_schedule.c
Labels: backport/2.11, backport/3.2, backport/3.3

#11098 wal: use existing logs sizes after restart
  changelogs/unreleased/gh-9811-checkpoint-wal-threshold-after-restart.md
  src/box/box.cc
  src/box/wal.c
  src/box/wal.h
  test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua
Labels: backport/2.11, backport/3.2, backport/3.3

#11279 box: rollback txns in WAL queue before in-flight tnxs
  changelogs/unreleased/gh-11179-wal-queue-rollback.md
  src/box/journal.c
  src/box/journal.h
  src/box/wal.c
  test/box-luatest/gh_11179_wal_queue_rollback_test.lua
Labels: backport/2.11, backport/3.2, backport/3.3
