Repository tarantool/tarantool, pull requests merged in 2025-04, with the labels that each got.

#11316 box: check if iterator was created when loading WAL GC consumers
  src/box/box.cc
  src/box/gc.c
  test/box-luatest/ghs_135_check_iterator_when_loading_gc_consumers_test.lua
Labels: full-ci

#11325 say: do not close stderr at exit
  src/lib/core/errinj.h
  src/lib/core/say.c
  src/main.cc
  test/app-luatest/gh_11323_write_to_stderr_at_exit_test.lua
Labels: full-ci

#11315 box: flush WAL queue on sync
  changelogs/unreleased/gh-11118-flush-journal-on-wal-sync.md
  src/box/box.cc
  src/box/wal.c
  test/box-luatest/gh_11118_flush_journal_on_wal_sync_test.lua
Labels: backport/2.11, backport/3.2, backport/3.3

#11322 relay: fix crash during shut down
  changelogs/unreleased/gh-9920-tx-with-dead-relay.md
  src/box/relay.cc
  src/lib/core/errinj.h
  test/replication-luatest/gh_9920_tx_with_dead_relay_test.lua
Labels: backport/2.11, backport/3.2, backport/3.3

#11331 salad: fix crash on insertion into bps tree with OOM conditions
  changelogs/unreleased/gh-11326-fix-crash-on-insertion-on-oom.md
  src/lib/salad/bps_tree.h
  test/unit/bps_tree.cc
Labels: full-ci, backport/3.3

#11352 box: fix out-of-bounds read in `index_opts_parse_layout()`
  src/box/index_def.c
Labels: full-ci

#11314 box: fix box.commit({wait = 'none'}) could yield
  changelogs/unreleased/gh-11224-fix-commit-wait-none-yield.md
  src/box/journal.c
  src/box/journal.h
  src/box/txn.c
  test/box-luatest/gh_11224_fix_commit_wait_none_journal_queue_test.lua
Labels: full-ci, backport/3.2, backport/3.3

#11366 [backport 3.3] memtx: raise an error when trying to use unsupported MVCC feature
  changelogs/unreleased/memtx-mvcc-forbid-multikey-and-func.md
  src/box/memtx_space.c
  test/box-luatest/gh_4348_transactional_ddl_test.lua
  test/box-luatest/memtx_mvcc_unsupported_features_test.lua
Labels: full-ci

#11359 box: fix session use-after-free
  changelogs/unreleased/gh-11267-fix-session-use-after-free.md
  src/box/session.c
  test/app-luatest/lib/tx_user_fiber_pool.cc
  test/app-luatest/tx_user_fiber_pool_test.lua
Labels: backport/3.3

#11368 Prepare changelogs for the 3.3.2 release
  changelogs/3.3.2.md
  changelogs/unreleased/config-failover-section-in-global-scope.md
  changelogs/unreleased/gh-10132-full-mp_int-support-sql.md
  changelogs/unreleased/gh-10709-luajit-fixes.md
  changelogs/unreleased/gh-10715-memtx-mvcc-conflict-with-prepared-sysview-txn.md
  changelogs/unreleased/gh-10766-synchro-crash-on-exit.md
  changelogs/unreleased/gh-10918-fix-log-message-truncate.md
  changelogs/unreleased/gh-11022-memtx-mvcc-point-holes-mhash-abort.md
  changelogs/unreleased/gh-11053-gc_consumers-record-lost-after-promote-and-restart.md
  changelogs/unreleased/gh-11055-luajit-fixes.md
  changelogs/unreleased/gh-11062-net-box-fetch-schema-restart-fix.md
  changelogs/unreleased/gh-11078-handle-cancel-of-request-in-wal-queue.md
  changelogs/unreleased/gh-11079-vy-cache-read-view-fix.md
  changelogs/unreleased/gh-11081-fix-wal-queue-size-accounting.md
  changelogs/unreleased/gh-11088-vy-tx-crash-on-timeout-fix.md
  changelogs/unreleased/gh-11091-synchro-queue-is-unlimited-after-local-recovery.md
  changelogs/unreleased/gh-11118-flush-journal-on-wal-sync.md
  changelogs/unreleased/gh-11140-vy-deferred-delete-rollback-fix.md
  changelogs/unreleased/gh-11163-vy-incomplete-run-gc-fix.md
  changelogs/unreleased/gh-11179-wal-queue-rollback.md
  changelogs/unreleased/gh-11224-fix-commit-wait-none-yield.md
  changelogs/unreleased/gh-11249-vy-space-truncate-under-load-fix.md
  changelogs/unreleased/gh-11267-fix-session-use-after-free.md
  changelogs/unreleased/gh-11326-fix-crash-on-insertion-on-oom.md
  changelogs/unreleased/gh-9811-checkpoint-wal-threshold-after-restart.md
  changelogs/unreleased/gh-9820-checkpoint-interval-after-restart.md
  changelogs/unreleased/gh-9920-tx-with-dead-relay.md
  changelogs/unreleased/gh-9965-wrong-numbers-comparison.md
  changelogs/unreleased/gh_9871_sequence_data_recovery_after_reset.md
  changelogs/unreleased/lua-call-runtime-priv-before-bootstrap.md
  changelogs/unreleased/luajit-prof-features.md
  changelogs/unreleased/luajit-prof-fixes.md
  changelogs/unreleased/memtx-mvcc-forbid-multikey-and-func.md
  src/box/lua/upgrade.lua
Labels: full-ci

#11287 replication.boostrap_strategy = native
  changelogs/unreleased/bootstrap-strategy-native.md
  src/box/lua/config/applier/box_cfg.lua
  test/config-luatest/native_bootstrap_strategy_test.lua
Labels: full-ci

#11381 config: allow guest to perform `failover.execute`
  changelogs/unreleased/allow-guest-call-failover-execute.md
  src/box/lua/config/applier/runtime_priv.lua
  src/box/lua/config/descriptions.lua
Labels: full-ci

#11264 box: introduce `txn_synchro_timeout` config option
  changelogs/unreleased/gh-10181-txn-synchro-timeout.md
  src/box/box.cc
  src/box/box.h
  src/box/errcode.h
  src/box/lua/cfg.cc
  src/box/lua/config/descriptions.lua
  src/box/lua/config/instance_config.lua
  src/box/lua/load_cfg.lua
  src/box/txn.c
  src/box/txn_limbo.c
  test/box/admin.result
  test/box/cfg.result
  test/box/error.result
  test/config-luatest/cluster_config_schema_test.lua
  test/config-luatest/instance_config_schema_test.lua
  test/replication-luatest/gh_10181_txn_synchro_timeout_test.lua
  test/replication-luatest/gh_7486_prohibit_roll_back_due_to_replication_synchro_timeout_test.lua
Labels: full-ci

#11392 Generate changelog for 3.4.0
  changelogs/3.4.0.md
  changelogs/unreleased/allow-bootstrap-in-ro-in-supervised-bs.md
  changelogs/unreleased/allow-guest-call-failover-execute.md
  changelogs/unreleased/bootstrap-strategy-native.md
  changelogs/unreleased/bump-metrics-to-1.3.0.md
  changelogs/unreleased/config-schema-unique-items.md
  changelogs/unreleased/config-transform-composite-type.md
  changelogs/unreleased/drop-long-select-warning.md
  changelogs/unreleased/early-make-bootstrap-leader.md
  changelogs/unreleased/forbid-repl-bootstrap-strategy-instance-scope.md
  changelogs/unreleased/gh-10181-txn-synchro-timeout.md
  changelogs/unreleased/gh-10182-add-ability-to-run-code-before-box-cfg.md
  changelogs/unreleased/gh-10647-vy-pp-np-iterator.md
  changelogs/unreleased/gh-10795-role-stop-on-shutdown.md
  changelogs/unreleased/gh-10842-learners-not-bootstrap-leaders.md
  changelogs/unreleased/gh-11111-index-quantile.md
  changelogs/unreleased/gh-11115-reconnect-timeout.md
  changelogs/unreleased/gh-11288-enabled-roles-api.md
  changelogs/unreleased/gh-1803-cross-engine-tx.md
  changelogs/unreleased/gh-8611-log-tables-in-json.md
  changelogs/unreleased/graceful-make-bootstrap-leader.md
  changelogs/unreleased/memtx-mvcc-forbid-multikey.md
  changelogs/unreleased/memtx-mvcc-func-index.md
  changelogs/unreleased/say-ratelimit-warning-fix.md
  changelogs/unreleased/single-instance-in-supervised-bs.md
  src/box/lua/upgrade.lua
Labels: full-ci

#11364 [backport 2.11] memtx: raise an error when trying to use unsupported MVCC feature
  changelogs/unreleased/memtx-mvcc-forbid-multikey-and-func.md
  src/box/memtx_space.c
  test/box-luatest/memtx_mvcc_unsupported_features_test.lua
Labels: full-ci

#11365 [backport 3.2] memtx: raise an error when trying to use unsupported MVCC feature
  changelogs/unreleased/memtx-mvcc-forbid-multikey-and-func.md
  src/box/memtx_space.c
  test/box-luatest/gh_4348_transactional_ddl_test.lua
  test/box-luatest/memtx_mvcc_unsupported_features_test.lua
Labels: full-ci

#11402 test: drop `box_index_scanner()` usage from perf and fuzz tests
  perf/lua/column_scan.lua
  perf/lua/column_scan_module.c
  test/fuzz/lua/test_engine.lua
Labels: full-ci

#11405 Fix FP compilation warning in func_adapter test
  test/unit/func_adapter_func.c
  test/unit/func_cache.c
Labels: full-ci, backport/3.2, backport/3.3, backport/3.4

#11395 memtx: handle OOM on statement rollback
  changelogs/unreleased/gh-11171-fix-crash-on-oom-statement-rollback.md
  src/box/index.cc
  src/box/index.h
  src/box/memtx_engine.cc
  src/box/memtx_hash.cc
  src/box/memtx_tree.cc
  src/box/txn.c
  src/box/txn.h
  src/lib/core/errinj.h
  test/box-luatest/memtx_oom_test.lua
  test/box/errinj_index.result
  test/box/errinj_index.test.lua
  test/fuzz/lua/test_engine.lua
Labels: full-ci

#11430 config-storage: reflect changed priv requirements
  doc/examples/config/config-storage/config.yaml
Labels: backport/3.2, backport/3.3, backport/3.4

#11443 box: add quiver engine initialization stub
  src/box/CMakeLists.txt
  src/box/box.cc
  src/box/engine.c
  src/box/engine.h
  src/box/quiver_engine.h
  src/trivia/config.h.cmake
Labels: full-ci
