Repository tarantool/tarantool, pull requests merged in 2025-01, with the labels that each got.

#11020 test: fix app-luatest/gh_7000_compat_module_test.lua
  test/app-luatest/gh_7000_compat_module_test.lua
Labels: code health, full-ci

#11025 [Backport 3.3] test: fix app-luatest/gh_7000_compat_module_test.lua
  test/app-luatest/gh_7000_compat_module_test.lua
Labels: full-ci

#11016 replication: fix crash on non-empty limbo exit
  changelogs/unreleased/gh-10766-synchro-crash-on-exit.md
  src/box/box.cc
  src/box/wal.c
  src/lib/core/errinj.h
  test/replication-luatest/gh_10766_shutdown_non_empty_limbo_test.lua
Labels: full-ci

#11029 [backport 3.3] replication: fix crash on non-empty limbo exit
  changelogs/unreleased/gh-10766-synchro-crash-on-exit.md
  src/box/box.cc
  src/box/wal.c
  src/lib/core/errinj.h
  test/replication-luatest/gh_10766_shutdown_non_empty_limbo_test.lua
Labels: full-ci

#11037 [backport 3.2] test: stabilize the gh_8650_add_is_sync_option test
  test/box-luatest/gh_8650_add_is_sync_option_test.lua
Labels: full-ci

#11026 ci: add action for automatic backporting
  .github/workflows/backport.yml
Labels: full-ci

#10509 say: replace panic macro with a function
  src/lib/core/say.c
  src/lib/core/say.h
  src/lua/utils.c
Labels: full-ci

#11040 test: fix flakiness in gh_7000_compat_module_test
  test/app-luatest/gh_7000_compat_module_test.lua
Labels: full-ci, backport/3.3

#11052 ci: use TarantoolBot for backporting
  .github/workflows/backport.yml
Labels: full-ci

#11051 vinyl: fix memory leak on error decoding row during compaction
  src/box/vy_run.c
Labels: full-ci

#10940 box.sequence: sequence_data recovery after reset
  changelogs/unreleased/gh_9871_sequence_data_recovery_after_reset.md
  src/box/box.cc
  src/box/request.c
  test/engine-luatest/gh_9871_sequence_restart_after_reset_test.lua
Labels: full-ci
