Repository tarantool/tarantool, pull requests merged in 2025-05, with the labels that each got.

#11428 test/fuzz: fix possible timeout in result chunks
  test/fuzz/luaL_loadbuffer/serializer.cc
Labels: full-ci, fuzzing

#11491 cmake: fix AppleClang detection
  cmake/compiler.cmake
Labels: full-ci, build issue, backport/2.11, backport/3.2, backport/3.3, backport/3.4

#11489 test: fix flakiness of the election + qsync stress test
  test/replication-luatest/election_qsync_stress_test.lua
  test/replication/election_qsync_stress.result
  test/replication/election_qsync_stress.skipcond
  test/replication/election_qsync_stress.test.lua
  test/replication/suite.ini
Labels: full-ci, backport/2.11, backport/3.2, backport/3.3, backport/3.4

#11511 core: move EE error injections to extras
  src/lib/core/errinj.h
  src/trivia/config.h.cmake
Labels: full-ci

#11509 cmake: fix LTO build on Fedora
  test/unit/CMakeLists.txt
Labels: build, full-ci, test, backport/2.11, backport/3.2, backport/3.3, backport/3.4

#11520 xlog: drop xdir type
  src/box/memtx_engine.cc
  src/box/recovery.cc
  src/box/vy_log.c
  src/box/wal.c
  src/box/xlog.c
  src/box/xlog.h
  test/unit/xlog.c
Labels: full-ci

#11444 config: add the `stateboard` section
  src/box/lua/config/descriptions.lua
  src/box/lua/config/instance_config.lua
  test/config-luatest/cluster_config_schema_test.lua
Labels: full-ci

#11529 lib: fix build error with fresh gcc compiler
  src/lib/tzcode/localtime.c
  test/unit/uuid.c
Labels: full-ci

#11525 ci: drop unused inputs for distrib workflow
  .github/workflows/distrib.yml
Labels: full-ci

#11519 ci: add Tarantool's revision in reusable workflows
  .github/workflows/config_jsonschema_check.yml
  .github/workflows/coverage.yml
  .github/workflows/debug.yml
  .github/workflows/debug_aarch64.yml
  .github/workflows/debug_asan_clang.yml
  .github/workflows/integration.yml
  .github/workflows/memtx_allocator_based_on_malloc.yml
  .github/workflows/out_of_source.yml
  .github/workflows/perf_micro.yml
  .github/workflows/release.yml
  .github/workflows/release_asan_clang.yml
  .github/workflows/release_clang.yml
  .github/workflows/release_lto.yml
  .github/workflows/release_lto_clang.yml
  .github/workflows/static_build.yml
  .github/workflows/static_build_cmake_linux.yml
Labels: full-ci

#11518 box: eliminate password leaks in logs
  changelogs/unreleased/gh-10653-passwords-are-logged-in-clear-text.md
  src/box/lua/load_cfg.lua
  test/box-luatest/gh_10653_passwords_are_logged_in_clear_text_test.lua
Labels: backport/2.11, backport/3.2, backport/3.3, backport/3.4

#11543 Generate changelog for 2.11.7
  changelogs/2.11.7.md
  changelogs/unreleased/change-er-invalid-dec-errcode.md
  changelogs/unreleased/gh-10132-full-mp_int-support-sql.md
  changelogs/unreleased/gh-10159-11292-mvcc-bitwise-key-comparison.md
  changelogs/unreleased/gh-10653-passwords-are-logged-in-clear-text.md
  changelogs/unreleased/gh-11014-sequential-json-fields-wrong-hash.md
  changelogs/unreleased/gh-11055-luajit-fixes.md
  changelogs/unreleased/gh-11078-handle-cancel-of-request-in-wal-queue.md
  changelogs/unreleased/gh-11118-flush-journal-on-wal-sync.md
  changelogs/unreleased/gh-11163-vy-incomplete-run-gc-fix.md
  changelogs/unreleased/gh-11179-wal-queue-rollback.md
  changelogs/unreleased/gh-11249-vy-space-truncate-under-load-fix.md
  changelogs/unreleased/gh-11294-vy-cache-read-view-fix.md
  changelogs/unreleased/gh-8782-yaml-decode-char-code-fix.md
  changelogs/unreleased/gh-9811-checkpoint-wal-threshold-after-restart.md
  changelogs/unreleased/gh-9820-checkpoint-interval-after-restart.md
  changelogs/unreleased/gh-9920-tx-with-dead-relay.md
  changelogs/unreleased/luajit-prof-features.md
  changelogs/unreleased/luajit-prof-fixes.md
  changelogs/unreleased/memtx-mvcc-forbid-multikey-and-func.md
  src/box/lua/upgrade.lua
Labels: full-ci

#11547 upgrade: add 2.11.7 to the downgrade versions list
  src/box/lua/upgrade.lua
Labels: backport/3.2, backport/3.3, backport/3.4

#11533 [backport: release/3.4] ci: add Tarantool's revision in reusable workflows
  .github/workflows/config_jsonschema_check.yml
  .github/workflows/coverage.yml
  .github/workflows/debug.yml
  .github/workflows/debug_aarch64.yml
  .github/workflows/debug_asan_clang.yml
  .github/workflows/default_gcc_centos_7.yml
  .github/workflows/integration.yml
  .github/workflows/memtx_allocator_based_on_malloc.yml
  .github/workflows/out_of_source.yml
  .github/workflows/perf_micro.yml
  .github/workflows/release.yml
  .github/workflows/release_asan_clang.yml
  .github/workflows/release_clang.yml
  .github/workflows/release_lto.yml
  .github/workflows/release_lto_clang.yml
  .github/workflows/static_build.yml
  .github/workflows/static_build_cmake_linux.yml
Labels: full-ci

#11534 [backport: release/3.3] ci: add Tarantool's revision in reusable workflows
  .github/workflows/config_jsonschema_check.yml
  .github/workflows/coverage.yml
  .github/workflows/debug.yml
  .github/workflows/debug_aarch64.yml
  .github/workflows/debug_asan_clang.yml
  .github/workflows/default_gcc_centos_7.yml
  .github/workflows/integration.yml
  .github/workflows/memtx_allocator_based_on_malloc.yml
  .github/workflows/out_of_source.yml
  .github/workflows/perf_micro.yml
  .github/workflows/release.yml
  .github/workflows/release_asan_clang.yml
  .github/workflows/release_clang.yml
  .github/workflows/release_lto.yml
  .github/workflows/release_lto_clang.yml
  .github/workflows/static_build.yml
  .github/workflows/static_build_cmake_linux.yml
Labels: full-ci

#11535 [backport: release/3.2] ci: add Tarantool's revision in reusable workflows
  .github/workflows/coverage.yml
  .github/workflows/debug.yml
  .github/workflows/debug_aarch64.yml
  .github/workflows/debug_asan_clang.yml
  .github/workflows/default_gcc_centos_7.yml
  .github/workflows/integration.yml
  .github/workflows/memtx_allocator_based_on_malloc.yml
  .github/workflows/out_of_source.yml
  .github/workflows/perf_micro.yml
  .github/workflows/release.yml
  .github/workflows/release_asan_clang.yml
  .github/workflows/release_clang.yml
  .github/workflows/release_lto.yml
  .github/workflows/release_lto_clang.yml
  .github/workflows/static_build.yml
  .github/workflows/static_build_cmake_linux.yml
Labels: full-ci

#11536 box: disallow alter of primary index with dependent secondary
  changelogs/unreleased/gh-10951-alter-pk-with-dependent-sk.md
  src/box/alter.cc
  test/box/tree_pk.result
  test/box/tree_pk.test.lua
  test/engine-luatest/gh_10951_memtx_alter_pk_with_dependent_sk_test.lua
Labels: full-ci

#11554 test: increase fiber slice for fast offset test
  test/box-luatest/gh_8204_fast_offset_test.lua
Labels: backport/3.2, backport/3.3, backport/3.4
